### ISSUE TITLE
Possible memory leak in 2.3.3-kh10/kh11

### ISSUE THREAD

**Issue by hamav8tor** [karlheyes/icecast-kh#101]
On CentOS 6.x 64-bit I am experiencing a lot of OOM killer action on icecast which seems to be leaking memory.  As the memory consumption sometimes reaches 1GB or so the CPU utilization also rises dramatically.

These instances are running on slave servers with a master containing about 1,000 source streams.

The number of clients on each slave numbers a few hundred.

Slave config:

<icecast>
    <limits>
        <clients>4096</clients>
        <sources>3000</sources>
	<workers>2</workers>

        <queue-size>524288</queue-size>
        <client-timeout>30</client-timeout>
        <header-timeout>15</header-timeout>
        <source-timeout>20</source-timeout>
        
        
        <burst-size>32768</burst-size>
    </limits>

    <authentication>
        
        <source-password>xxxxxxx</source-password>
        
        <relay-password>xxxxxxx</relay-password>

        
        <admin-user>admin</admin-user>
        <admin-password>xxxxxxxxxx</admin-password>
    </authentication>

    
    <hostname>slave.host.net</hostname>

    
    <listen-socket>
        <bind-address>127.0.0.1</bind-address>
        <port>8000</port>
        
        
    </listen-socket>
    

    <master-server>master.host.net</master-server>
    <master-server-port>8000</master-server-port>
    <master-update-interval>15</master-update-interval>
    <master-password>xxxxxxxxx</master-password>
    <master-relay-auth>1</master-relay-auth>

    
    <relays-on-demand>1</relays-on-demand>

    <fileserve>1</fileserve>

    <paths>
        
        <basedir>/home/icecast</basedir>

	
	<x-forwarded-for>127.0.0.1</x-forwarded-for>

        
 
        <logdir>/var/log/icecast</logdir>
        <webroot>/usr/share/icecast/web</webroot>
        <adminroot>/usr/share/icecast/admin</adminroot>
        <pidfile>/var/log/icecast/icecast.pid</pidfile>
    </paths>

    <logging>
        <accesslog>access.log</accesslog>
        <errorlog>error.log</errorlog>
        
        <loglevel>2</loglevel> 
        <logsize>10000</logsize> 
        
        <logarchive>0</logarchive>
    </logging>

    <security>
        <chroot>0</chroot>
        <changeowner>
            <user>icecast</user>
            <group>nobody</group>
        </changeowner>
    </security>
</icecast>

**Comment by karlheyes** [comment]
I have updated the xsl parsing code recently to handle some odd cases, is this still an issue with the master build?

karl.

**Comment by hamav8tor** [comment]
I will do some more testing on this in the next 2 weeks and let you know.  In the interim I had taken other measures to "protect" the Icecast server from excessive access to this XSL.

**Comment by karlheyes** [comment]
no further comments on this, reopen of it needs more work.

karl.
