### ISSUE TITLE
AAC stream in FLV container with SSL disconnects

### ISSUE THREAD

**Issue by dtouch3d** [karlheyes/icecast-kh#104]
After enabling ssl and authentication, requesting an aac stream through ssl returns only a few KB of data and then the connection drops. Originally I thought this was in jPlayer only but VLC, even the trusty curl, do the same.

In error.log

    DBUG connection/check_for_filtering listener has requested FLV                                                                                                                                     
    DBUG stats/modify_node_event update "global" client_connections (1)                                                                                                                                
    DBUG auth/auth_add_listener adding client for authentication                                                                                                                                       
    DBUG auth/queue_auth_client starting auth thread 0                                                                                                                                                 
    DBUG auth/queue_auth_client auth on /mystream has 1 pending                                                                                                                                        
    DBUG auth/auth_run_thread Authentication thread 63 started for /mystream                                                                                                                           
    DBUG auth/auth_run_thread 1 client(s) pending on /mystream                                                                                                                                         
    DBUG auth_url/url_add_listener handler 63 sending request                                                                                                                                          
    DBUG auth_url/url_add_listener handler 63 request finished                                                                                                                                         
    DBUG stats/modify_node_event update "/mystream" listener_connections (1)                                                                                                                           
    INFO source/source_add_listener max on /mystream is -1 (cur 0)                                                                                                                                     
    DBUG stats/modify_node_event update "global" listeners (1)                                                                                                                                         
    DBUG stats/modify_node_event update "global" listener_connections (1)                                                                                                                              
    DBUG auth/auth_run_thread Authenication thread 63 shutting down                                                                                                                                    
    DBUG auth/auth_release ...refcount on auth_t /mystream is now 1                                                                                                                                    
    DBUG source/locate_start_on_queue XXX.XXX.216.148 Joining queue on /mystream (79755, 15077)                                                                                                        
    DBUG flv/flv_meta_increase 3 array elements                                                                                                                                                        
    INFO source/source_read listener count on /mystream now 1                                                                                                                                          
    DBUG stats/modify_node_event update "/mystream" listeners (1)                                                                                                                                      
    DBUG stats/modify_node_event update "/mystream" listener_peak (1)                                                                                                                                  
    DBUG stats/modify_node_event update "global" listeners (0)                                                                                                                                         
    DBUG auth/queue_auth_client starting auth thread 0                                                                                                                                                 
    DBUG auth/queue_auth_client auth on /mystream has 1 pending                                                                                                                                        
    DBUG auth/auth_run_thread Authentication thread 63 started for /mystream                                                                                                                           
    DBUG auth/auth_run_thread 1 client(s) pending on /mystream                                                                                                                                         
    DBUG auth_url/url_remove_listener ...handler 63 sending request                                                                                                                                    
    DBUG auth_url/url_remove_listener ...handler 63 request complete 

No reason is stated about the client disconnection. The whole setup works fine without ssl.

**Comment by dtouch3d** [comment]
Update: This must be a bug specific to the FLV enapsuclation of AAC because with MP3 it does not reproduce.

**Comment by karlheyes** [comment]
hmm, ok, will have to duplicate that to see what is going on. Does it require auth to be involved?

karl.

**Comment by dtouch3d** [comment]
No it doesn't. My bad.

**Comment by karlheyes** [comment]
I tried with both kh11 and latest build, relaying an aac stream and then requesting the aac stream from an ssl port and it seems to work. Is there anything else involved like intro content?  I see the log report the reduction in the global listener count but not the source listener count which is odd.

karl.

**Comment by dtouch3d** [comment]
Did you try with "?type=.flv" appended ? In my setup it works just fine without it but disconnects otherwise.

**Comment by karlheyes** [comment]
I did try it and it did work with the setting over ssl.   Can you set up a duplicate icecast relaying the stream on another ssl port  to verify it on that instance, I may be able to see more from that instance without affecting your existing live setup.  Getting a repeatable case is half the battle.

karl.

**Comment by dtouch3d** [comment]
Did you try it on your local machine ? I just noticed that setting up a relay on my local machine and requesting the stream works fine, but when icecast runs on a remote server it closes the connection. When I request the stream from within the server with curl through ssh there is no problem. So it seems that the problem manifests only for remote connections.

I have set up a relay at https://83.212.124.196:19800/chr_80s?type=.flv

it's with a self signed certificate, so be sure to whitelist it. I typically test with

```
curl https://83.212.124.196:19800/chr_80s\?type\=.flv -k -o /dev/null
```

**Comment by karlheyes** [comment]
After a bit of head scratching and stressing things in different ways, I think I've flushed this one out.  It's not specifically aac related so could affect mp3 but it is tied to the use of the SSL and how FLV is made to fit it.  The key aspect though is when there is stalling going on, so if there are larger data transfers on longer links, so the remote nature of the listener was a factor that plays into it.

The patch is committed to github master so if you can verify the issue is no more.

karl.

**Comment by dtouch3d** [comment]
Yeap, that fixed it. Thank you so much!
