### ISSUE TITLE
Content-Disposition header syntax wrong

### ISSUE THREAD

**Issue by defmtog** [karlheyes/icecast-kh#107]
i'm using an http client to fetch the stream status via the status2.xsl file. i get the following error:

    Unable to parse header: Content-Disposition = attachment; filename=file.txt

from my reading of the rfc, the Content-Disposition header should be a ":" separator, not a "="?

http://www.w3.org/Protocols/rfc2616/rfc2616-sec19.html#sec19.5.1

**Comment by karlheyes** [comment]
That should be fixed up now in master. I've also added quotes around the filename.  I think I just copied the line from buildm3u so it must be a old issue.

karl.

**Comment by defmtog** [comment]
thanks!
