### ISSUE TITLE
HEAD vs GET different response.

### ISSUE THREAD

**Issue by cdgraff** [karlheyes/icecast-kh#108]
Hi,  I'm setting HTTP monitoring app, to check the availability of my stream, like pingdom or uptimerobot.

After test this, I see that always see 200 ok inclusive when my stream is not online, and of course this tools don't send the alerts.

some reason to do this?

curl -X GET -I http://icecast/stream
HTTP/1.0 404 Not Available
Content-Type: text/html

curl -X HEAD -I http://icecast/stream
HTTP/1.1 200 OK
Access-Control-Allow-Origin: *
Access-Control-Allow-Headers: Origin, Accept, X-Requested-With, Content-Type
Access-Control-Allow-Methods: GET, OPTIONS, HEAD, STATS

Thanks!

**Comment by karlheyes** [comment]
HEAD is not the best way to check for this, it probably does need tying into joining the streams but that would mean kicking off on-demand relays. I suspect we only want to reports the headers if there is an active stream only.   Make your own custom xsl for now, it would not need to report much if you just want to test for it being there or active.

karl.

**Comment by karlheyes** [comment]
After an issue that needed similar work when processing headers, the HEAD mechanism should also work as you require.  Please verify.

karl.

**Comment by aferrari-technisys** [comment]
thanks Karl, I'll upgrade and test...

**Comment by cdgraff** [comment]
Work well now! thanks
