### ISSUE TITLE
Question: Listeners/Connections

### ISSUE THREAD

**Issue by mr-deamon** [karlheyes/icecast-kh#109]
Hi there
Using KH10, currently planing the migration to KH11.

I started having too many connection errors, even if my listeners did not increase on the server. If I compare connections and listeners, the connections is almost twice as high as the listener-counter. Its 8k connections and 4k listeners. Netstat -an does show about the same number as the listener-count. Do you have any idea why the count is this high compared with a constant listener-count?

Thank you!
Chris

**Comment by karlheyes** [comment]
connections has always been an accumulated count, like slow_listeners or other _connections stats.

karl.
