### ISSUE TITLE
Memoryleak with URL-Auth?

### ISSUE THREAD

**Issue by mr-deamon** [karlheyes/icecast-kh#111]
Hi there
I recently switched from cmd to URL-authentication for my streams. It works well, but i think there might be a memory leak somewhere.
If I start Icecast (tested both, 2.3.3 KH11 and 2.4.4 KH1) the memory is increasing linear and will cause to crash the process about 24h later. This server serves about 4k connections peak and it authenticates every request. There are about 250 requests/min to the auth-database (which is working well, this should not be the problem).

I'd be happy to help out with logs!

Thanks a lot
Chris

**Comment by karlheyes** [comment]
What settings have you specified for the auth and are you reporting any options within the auth responses, like intro, location or mountpoint that could be an issue.  Any odd message in the error log relating to auth?

karl.

**Comment by mr-deamon** [comment]
Thanks for your quick reply!

The settings are:
```
<authentication type="url">
    <option name="listener_add" value="https://geostream.domain.tld/api/streams/icecastauth" />
</authentication>
```
For each mountpoint. Maybe it's important that there are a dozen aliases defined for mountpoints which have their names changed.

There is not a single auth/* message which is not a DBUG message. If i scan through these DBUG-lines, there is nothing special, it's just always the four same lines.

**Comment by karlheyes** [comment]
Can you try something to help pinpoint the leak, it will mean a rebuild and restart of icecast though.

make clean
make CFLAGS="-DMY_ALLOC -g"
make install   or whatever you prefer to do to install this

leave it to run, periodically you can collect stats with 

http://admin:pw@host:port/admin/alloc

any leak within the allocations made directly by icecast should show as increasing over time, allocations in the libraries like libxml2 won't but it will help to narrow it down.

karl.

**Comment by mr-deamon** [comment]
Thank you. By mistake i compiled icecast without libcurl-support (-devel was not installed), and is running smothly and without any increasing allocations since then. I fixed my fault this morning by re-compile it with libcurl, i'll let you know when i see something!

chris

**Comment by mr-deamon** [comment]
Good morning Karl
There is only one value constantly growing and not really connected to the listener-number: it's validate_mpeg:805. It is starting at 9238510 and ended with 30797488. You can have a look at the numbers yourself: https://gist.github.com/mr-deamon/abef1ce8243adc1a2c17

Because of my mistake before (see my last comment), I'm pretty sure that is has to do with authentication. When it was not working, there was no memory-increase...

Have a good day!
Chris

**Comment by karlheyes** [comment]
Can you tell me about what you have in the set up, I don't see any counts in the table,  how many sources do you have, what queue-sizes do you have. Are you supplying intro via the auth?

karl.

**Comment by mr-deamon** [comment]
Hi Karl
Sorry for my late review, i was away for two weeks...

* The setup is two masterservers, 2x6 edgeservers pointing to the masters with mount and fallback.
* There are about 90 channels (or 180 if you count backup-mountpoints).
* The queue-size value is not set in the config-file
* We do not use Intros

I'll try to redo my test with the count-numbers, sorry about that...
chris

**Comment by mr-deamon** [comment]
I can't really make sense of the new data. There is no grave going clearly up, although there are a few pointing in this direction. An intresting fact is that my loadbalancer disabled the server at 3AM UTC this morning and my load-fetch-script has a gap between 7:30pm UTC and 6am. (The loadbalancer has observed a "timeout in body phase", the load-fetch script only logged connection-timeout).
The data you'll see [here](https://gist.github.com/mr-deamon/fb6cd952634a7fe9905a) is a representation of 19h in which the memory was growing as long there were users connecting to the server. Gowth stopped at 3am when my LB disabled this server. RAM (and SWAP) stayed high even if there were no new connections, and continued to grow when I re-enabled the server this morning.
The number of listeners within the given data is constantly going back from 3k to about 400 at it's lowest, first because it was nighttime, second because the LB deactivated the server at 3am. Until this time though, there were still new connections opened.

Do you have any idea?

**Comment by mr-deamon** [comment]
Hi Karl
Have you had a chance to look at this? I'm curious why i am the only one with this issue, im sure the URL-Auth feature is used by a lot of customers?!

Chris

**Comment by karlheyes** [comment]
not much to go on really, the table you produced does have a lot of refbuf_copy, more than expected. There was a fix around jul 5th to resolve a requeue issue which may affect those.

It looks like you have about 190 sources (all relays) taking in the region of 30Meg of queues, which seems sensible for the typical queue size. Nothing else jumps out as bad but I'm not seeing much else to work on.  Make sure you are on the latest work to deal with the _copy and let me know the figures.

karl.


karl

**Comment by mr-deamon** [comment]
Thanks for your reply! I'll try my luck with the new version, but my current test is using a version compiled with a newer version of libcurl. Until now it was compiled using V7.29, that seems to be quite old. Now there are two servers running with libcurl-7.44. I'll keep you posted!

Chris

**Comment by mr-deamon** [comment]
It looks like it's libcur-related. Now 2.4.4 KH1 is running on the latest libcurl-version (7.4.4) and it's been a week on full load without increasing memory.
I'll close this, thanks for your investigations and your work!!
Chris
