### ISSUE TITLE
Duplicate parameters in /admin/listmounts request

### ISSUE THREAD

**Issue by alvassin** [karlheyes/icecast-kh#113]
When performing request to /admin/listmounts i see the following:

```xml
<source mount="/11-31.mp3">
<listeners>0</listeners>
<Listeners>0</Listeners>
<authenticator>command</authenticator>
<Connected>26861</Connected>
<content-type>audio/mpeg</content-type>
</source>
```

Why there are two listeners elements? Is that a mistake? Or they have different meaning? (for my server they have same values)

If they have same meaning, which element is correct, with lowercase or uppercase first character?

**Comment by karlheyes** [comment]
For backward compatibility.  They are the same value but the case of the letter was making a mess between versions of xsl or the way some have done comparisons in there own xml parsing. so I just added the extra stat to flush it out, you should really do case insensitve test, but historically there has been a mix of case causing some confusion. 

karl.

**Comment by alvassin** [comment]
Thanks a lot for clarification!
