### ISSUE TITLE
What data is accessible in XSLT templates?

### ISSUE THREAD

**Issue by alvassin** [karlheyes/icecast-kh#114]
As i understand, there are some raw requests supported in icecast, that could be formatted with XSLT templates to make custom format.

Can you please tell me, where i can find full list of information i am able to display in XSLT templates in /admin/ and in /web/ folders?

**Comment by karlheyes** [comment]
The /admin/stats is the main list of stats you can use for xsl expansion in either web or admin.  If a source is flagged as hidden then it is only available via /admin, listener details are only via /admin  pages if you specify a ?mount=/.... parameter.  There are some specific /admin request reserved like /admin/metadata but you can use your own custom xsl pages in adminroot if you wish.

karl.

**Comment by alvassin** [comment]
Thank you for response!

Perhaps there are some RAW commands for /web/ that are present in /admin/?

For example, i can access /admin/ - information about server & sources, /admin/listmounts - information about sources & so on.

**Comment by karlheyes** [comment]
You don't really have raw commands for web root, you either have static files or xsl translations, where the xsl translates public xml stats.  Those stats can be seen in /admin/stats but if a stat is flagged as hidden (only really applies to sources) then it will not be listed for webroot translations.

karl.

**Comment by alvassin** [comment]
Ok, got it! Thanks a lot for help!

**Comment by alvassin** [comment]
Hmm.. i currently use command /admin/listmounts?with_listeners to retrieve all listeners information. Is it possible to display this data via xsl located in /admin folder (with some transformation)?

**Comment by karlheyes** [comment]
That was never intended to be used in general, as it can produce a huge list,  it's only really tied to the listmounts[.xsl] hook.  You could tailor the listmounts.xsl page for it, but it is the only one that would get those details in full.

karl.

**Comment by alvassin** [comment]
Ok. Thanks for reply!
