### ISSUE TITLE
How does /admin/managerelays.xsl?relay=/mount&enable=0 works?

### ISSUE THREAD

**Issue by alvassin** [karlheyes/icecast-kh#115]
Does it disable mount until icecast will be rebooted, until config reload.. or how should it work?

**Comment by karlheyes** [comment]
it disables the relay until re-enabled but the setting is not preserved over restarts so a restart of icecast will clear that setting.  Note that there is also an <enable> boolean in <relay> that can set the initial state of the relay on xml loading.

karl.

**Comment by alvassin** [comment]
Got it! Thank you!
