### ISSUE TITLE
Same problem Tunein URL mp3

### ISSUE THREAD

**Issue by edinsof** [karlheyes/icecast-kh#116]
Hi i update icecast-kh and i'm getting same problem:

Icecast 2.4.0-kh1 Tunein URL mp3
https://github.com/karlheyes/icecast-kh/issues/112

**Comment by karlheyes** [comment]
can you get me the tcpdump/wireshark capture from this.

karl.

**Comment by edinsof** [comment]
how do it?

**Comment by karlheyes** [comment]
eg as root do 
tcpdump -w capture -s 0 -i eth0  port 8000

try to connect with the player, when it definitely has failed then ctrl-C the tcpdump and email me the 'capture' file. 

You may need to use something different to eth0 or 8000 if your system is configured differently

karl.

**Comment by edinsof** [comment]
![icecast](https://cloud.githubusercontent.com/assets/3094013/9024265/365d3780-388b-11e5-8297-f3c828bddfd6.png)


Capture file:
http://expirebox.com/download/d5693d31af80ddff1b4e8dd5a6ade00d.html

**Comment by karlheyes** [comment]
I think this is down to a poor reaction to short writes when using chunked responses.  You could actually disable chunked responses (?_hdr=8) but I've just committed to change to fix the problem. My tests here seem to be good enough for that, can you verify against latest master?

karl.

**Comment by edinsof** [comment]
Fixed thank you :)

**Comment by edinsof** [comment]
Hi i updated to 2.4.0-kh2 and getting same problem again. issue #112

**Comment by karlheyes** [comment]
my oversight, in fixing an iphone issue it broke chrome which also uses a range header but in a slightly different way. The master tree on github should now be fixed for that.

karl.

**Comment by edinsof** [comment]
Fixed thank you :)
