### ISSUE TITLE
connected single user are multiplied

### ISSUE THREAD

**Issue by felipegabriel** [karlheyes/icecast-kh#120]
177.0.99.xxx	159	335904	stagefright/1.2 (Linux;Android 5.0.2)	Kick
177.0.99.xxx	156	256416	stagefright/1.2 (Linux;Android 5.0.2)	Kick
177.0.99.xxx	147	379488	stagefright/1.2 (Linux;Android 5.0.2)	Kick
177.0.99.xxx	147	485064	stagefright/1.2 (Linux;Android 5.0.2)	Kick
177.0.99.xxx	139	259824	stagefright/1.2 (Linux;Android 5.0.2)	Kick
177.0.99.xxx	139	314688	stagefright/1.2 (Linux;Android 5.0.2)	Kick
177.0.99.xxx	133	277368	stagefright/1.2 (Linux;Android 5.0.2)	Kick
177.0.99.xxx	133	316368	stagefright/1.2 (Linux;Android 5.0.2)	Kick
177.0.99.xxx	125	353988	stagefright/1.2 (Linux;Android 5.0.2)	Kick
177.0.99.xxx	121	414576	stagefright/1.2 (Linux;Android 5.0.2)	Kick
177.0.99.xxx	113	351360	stagefright/1.2 (Linux;Android 5.0.2)	Kick
177.0.99.xxx	113	421812	stagefright/1.2 (Linux;Android 5.0.2)	Kick
177.0.99.xxx	112	226440	stagefright/1.2 (Linux;Android 5.0.2)	Kick
177.0.99.xxx	106	382440	stagefright/1.2 (Linux;Android 5.0.2)	Kick
177.0.99.xxx	103	378720	stagefright/1.2 (Linux;Android 5.0.2)	Kick
177.0.99.xxx	100	301536	stagefright/1.2 (Linux;Android 5.0.2)	Kick
177.0.99.xxx	100	279336	stagefright/1.2 (Linux;Android 5.0.2)	Kick
177.0.99.xxx	81	257136	stagefright/1.2 (Linux;Android 5.0.2)	Kick
177.0.99.xxx	79	307824	stagefright/1.2 (Linux;Android 5.0.2)	Kick
177.0.99.xxx	79	306504	stagefright/1.2 (Linux;Android 5.0.2)	Kick

this is a unique User multiplied several times over this should be only one.
could be an option to accept only one User for IP and user agent
ty

**Comment by karlheyes** [comment]
It's one of those stupidly broken players, although last I heard was they only used 2 connections, but I guess this one breaks things really badly.  Can you confirm whether you can kick all but the earliest one to maintain the playback (lowest id)

karl.

**Comment by felipegabriel** [comment]
I can kick all, they always come back up to the maximum allowed causing problems playing

**Comment by karlheyes** [comment]
if you kick all then I would not be surprised, the question is which one is used for playback.  I think most web browser based players do multiple requests, audacious is another that for some reason opens multiple connections, iphone does something similar.  Each has a quirk, and blocking as you suggest sounds like it will keep spamming the server with retries and still not play.

Most so far just request the stream and close the surplus connections after a short amount, but that one keeps the link open.  It may be best to just block the stagefright useragent or provide a simple page to say it's broken.

karl.

**Comment by felipegabriel** [comment]
I'll try to work it in the firewall. I really can not block useragent.
it makes my bad hearing report. I can raise the maximum allowed.
the biggest problem is the report for my listeners =(

Thank you very attentive
