### ISSUE TITLE
Icecast 2.4.0-kh2 and mozilla firefox

### ISSUE THREAD

**Issue by nesale** [karlheyes/icecast-kh#123]
If you listen link http://77.91.78.34/jazz128.mp3 in mozilla firefox you can hear that on air marriage

if you listen link in google chrome (vlc) it's ok

in old version icecast kh it's ok

**Comment by felipegabriel** [comment]
I also have this problem

**Comment by leonardder** [comment]
Comfirmed.

**Comment by karlheyes** [comment]
Can you verify the stream against the latest master, I suspect it's the range header issue.  You can relay it, if it is in production.

karl.

**Comment by nesale** [comment]
Karl, 
1. The icecast server can add the desired header?
2. Is there a right approach how to rollback to a previous version?

**Comment by karlheyes** [comment]
1. If it's related to the range header then it's not just a matter of adding a header, the browsers issue multiple requests like bytes 0-1 or 0-  and the response can be 206 or 200 if it's a file of a known size.

2. just get the rollback snapshot, build if you haven't ready and make install. It will overwrite the previous binary.

karl.

**Comment by felipegabriel** [comment]
fix?

**Comment by karlheyes** [comment]
I tried this in FF on kh3 (win32) and it played fine.

karl.

**Comment by cdgraff** [comment]
Hi @karlheyes, 

I has upgraded to latest commit and still the issue there, can test here:
http://c3sl1.mediainbox.net:8000/cadena3.mp3

Thanks!
Ale

**Comment by karlheyes** [comment]
Can I have a description of what I'm looking for. Placing these URLs in FF does seems to play here, I get some stuttering but that could be from my virtualbox/pulseaudio hookup.  What version did it work with so that I can see if there are any header differences, although it looks fairly trivial.

karl.

**Comment by cdgraff** [comment]
@karlheyes, that stuttering is the issue... is not your pulseaudio... this is the issue we saw.
here a few seconds recorded from my desktop:
https://www.dropbox.com/s/1gf9q5qps60ocwz/2015-11-13%2020-04-03.mp4?dl=0

I has compiled first with this commit and the issue be there, today i has upgraded to latest and same problem:
https://github.com/karlheyes/icecast-kh/commit/244e5006b8f3f475598e0f4001e46c19a29f9591

But look like is not only Icecast-kh issue... nimbleStreamer has similar problem (i has shared the link they developer create into FF support)

But this link is the default Icecast release (Icecast 2.4.2) and don't fail:
http://c3sl2.mediainbox.net:8000/cadena3.mp3

thanks!
Ale

**Comment by karlheyes** [comment]
Can you check the latest master now, when testing different combinations, it seemed like the accept-ranges header was causing the problem. Not sure why but I don't think it's needed for anything so now removed.  I've added a Date header just to keep to standards as well.

karl.

**Comment by cdgraff** [comment]
Hi @karlheyes after many hours of testing, I can say that was fixed the issue into FF with this latest change.

Thanks for the great support as always do!.
Alejandro
