### ISSUE TITLE
Upgrade to Latest commit 270abdb and streaming go down

### ISSUE THREAD

**Issue by edinsof** [karlheyes/icecast-kh#131]
Hi karl 

Latest commit 270abdb 4 days ago

Streaming show this info on status page and after thid streaming go down, i need restart stream 
 [2016-01-21 09:00:18] EROR connection/wait_for_serversock signalfd descriptor became invalid, doing thread restart

![2016-01-21 a las 4 10 45 p m](https://cloud.githubusercontent.com/assets/3094013/12494907/b6a3e360-c05a-11e5-93f1-ca947173314a.png)

**Comment by karlheyes** [comment]
This looks like an incorrect FD migrating, being closed and that then affects something else like a worker or logging which may explain another bug report.  Can you confirm if you are running with -b (backrground) with this?

karl.

**Comment by edinsof** [comment]
yes icecast is running -b with centovacast control panel

**Comment by karlheyes** [comment]
just committed a fix.  could of triggered with 404 responses.

karl.
