### ISSUE TITLE
Dynamic script on_connect

### ISSUE THREAD

**Issue by epscylonb** [karlheyes/icecast-kh#136]
I'm interested in firing a script whenever a source/mount connects.

In icecast-kh we can only do this if we know what the mount point is ahead of time and put it in the config file.

The latest icecast (2.4+) supports a 'default mount point' which can be used to set up a script to fire whenever any new mount point is created.

Are there any plans to backport this functionality into icecast-kh?.

I could be willing to do the work myself but before even thinking about it I want to make sure:

a) it would be welcome.
b) that there isn't already a way to achieve the same thing.

Any help appreciated.

**Comment by karlheyes** [comment]
actually you have been able to do this for some time, in a more flexible way.  They are called wildcard mountpoints, eg

<mount>
    <mount-name>/a*.mp3</mount>
    <on-connect>....</on-connect>
    <intro>/intros/${mount}</intro>
</mount>

and you can have any number. obviously if you have a clash, ie 2 mounts matching then one is picked over the other.  There really needs to be a priority defined, to be implemented.

karl.

**Comment by epscylonb** [comment]
Ah, that works great. Thanks.
