### ISSUE TITLE
segfault - error 4 in libcrypto.so.1.0.0

### ISSUE THREAD

**Issue by ibcs01** [karlheyes/icecast-kh#142]
Hi Karl,

It's been a while. Hope you're doing well? Here everything is just fine.

Just wanted to ask you if you could look into a segfault we receive every few days. We have created a workaround by automatically restarting Icecast if it does occur, but it does make our platform somewhat unstable and I hope you could look into this and fix the issue. 

I have reported on this before, so you could look my old posts up.

Anyway, we have built Icecast using make debug and here are the files you nee to analyse the crash:
http://tiny.cc/tci0ey

Hope you could provide a solution, or point us in the right direction.
Thanks in advance for your help!

Best regards,
Sven

**Comment by karlheyes** [comment]
hi, been somewhat busy with things.  Is this still a problem and is this the kh3 release and from a post kh3 build?   Can you verify the libssl version you are using as well?

karl.

**Comment by djamps** [comment]
I would like to add that since enabling SSL we have been seeing this issue as well - regular segaults in libcrypto which freeze (but not kill) icecast.   It happens usually within a few hours of icecast starting once lots of listeners are connected via SSL.    Tried both Ubuntu and CentOS and got the same issues so I doubt it's something to do with the SSL libs.    SSL streaming basically unusuable which is really dissapointing given the way things are going these days with secure content warnings / blocking.

**Comment by karlheyes** [comment]
segfaults do not cause a freeze unless something else is trapping the handler. If you get a freeze then you can run gcore <pid> to grab a core dump without terminating the process, a normal segfault can generate a core if your system allows for it, even a catchsegv may be helpful.  I cannot comment on a 2.4.3 build but there should be no issues on the master build on the kh tree.

karl.

**Comment by djamps** [comment]
The behavior in ubuntu was different but end result similar -- after some time new connections to the mount point (but NOT the web interface) would result in SSL_ERROR_BAD_MAC_ALERT.   A couple hours after that Icecast would die, but I did not see a segfault in syslog.    In CentOS, you get the libcrypto segfault and then no connections are possible at all to SSL/non-SSL interfaces.

**Comment by djamps** [comment]
Update - I was wrong about icecast freezing -- it dies along with the sefgault.   Running catchsegv and waiting for the next.

**Comment by djamps** [comment]
*** Segmentation fault
Register dump:

 RAX: 00000000e563af21   RBX: 0000000015da5465   RCX: 000000009e4e645e
 RDX: 00000000c51ac30f   RSI: 000000007e28d618   RDI: 00000000b5c7939a
 RBP: 00000000915f9a37   R8 : 00007fba1c2ad160   R9 : 000000355ffe3ffb
 R10: 000000355ffe07fb   R11: 000000355fc769c0   R12: 000000355ffe07fb
 R13: ffffffffffffffc0   R14: 0000000000000018   R15: 00007fba1c2ad17c
 RSP: 00007fba2de21990

 RIP: 000000355fc758d8   EFLAGS: 00010206

 CS: 0033   FS: 0000   GS: 0000

 Trap: 0000000e   Error: 00000004   OldMask: 7ffafabf   CR2: 5ffe4000

 FPUCW: 0000037f   FPUSW: 00000000   TAG: 00000000
 RIP: 00000000   RDP: 00000000

 ST(0) 0000 0000000000000000   ST(1) 0000 0000000000000000
 ST(2) 0000 0000000000000000   ST(3) 0000 0000000000000000
 ST(4) 0000 0000000000000000   ST(5) 0000 0000000000000000
 ST(6) 0000 0000000000000000   ST(7) 0000 0000000000000000
 mxcsr: 1f80
 XMM0:  00000000000000000000000000000000 XMM1:  00000000000000000000000000000000
 XMM2:  00000000000000000000000000000000 XMM3:  00000000000000000000000000000000
 XMM4:  00000000000000000000000000000000 XMM5:  00000000000000000000000000000000
 XMM6:  00000000000000000000000000000000 XMM7:  00000000000000000000000000000000
 XMM8:  00000000000000000000000000000000 XMM9:  00000000000000000000000000000000
 XMM10: 00000000000000000000000000000000 XMM11: 00000000000000000000000000000000
 XMM12: 00000000000000000000000000000000 XMM13: 00000000000000000000000000000000
 XMM14: 00000000000000000000000000000000 XMM15: 00000000000000000000000000000000

Backtrace:
/usr/lib64/libcrypto.so.10[0x355fc758d8]

Memory map:

00400000-00434000 r-xp 00000000 08:03 51775118                           /usr/local/bin/icecast
00634000-00635000 rw-p 00034000 08:03 51775118                           /usr/local/bin/icecast
00635000-00636000 rw-p 00000000 00:00 0
018f4000-02e33000 rw-p 00000000 00:00 0                                  [heap]
3555400000-3555420000 r-xp 00000000 08:03 1048582                        /lib64/ld-2.12.so
355561f000-3555620000 r--p 0001f000 08:03 1048582                        /lib64/ld-2.12.so
3555620000-3555621000 rw-p 00020000 08:03 1048582                        /lib64/ld-2.12.so
3555621000-3555622000 rw-p 00000000 00:00 0
3555800000-3555802000 r-xp 00000000 08:03 1048672                        /lib64/libdl-2.12.so
3555802000-3555a02000 ---p 00002000 08:03 1048672                        /lib64/libdl-2.12.so
3555a02000-3555a03000 r--p 00002000 08:03 1048672                        /lib64/libdl-2.12.so
3555a03000-3555a04000 rw-p 00003000 08:03 1048672                        /lib64/libdl-2.12.so
3555c00000-3555d8a000 r-xp 00000000 08:03 1048584                        /lib64/libc-2.12.so
3555d8a000-3555f8a000 ---p 0018a000 08:03 1048584                        /lib64/libc-2.12.so
3555f8a000-3555f8e000 r--p 0018a000 08:03 1048584                        /lib64/libc-2.12.so
3555f8e000-3555f90000 rw-p 0018e000 08:03 1048584                        /lib64/libc-2.12.so
3555f90000-3555f94000 rw-p 00000000 00:00 0
3556000000-3556017000 r-xp 00000000 08:03 1048986                        /lib64/libpthread-2.12.so
3556017000-3556217000 ---p 00017000 08:03 1048986                        /lib64/libpthread-2.12.so
3556217000-3556218000 r--p 00017000 08:03 1048986                        /lib64/libpthread-2.12.so
3556218000-3556219000 rw-p 00018000 08:03 1048986                        /lib64/libpthread-2.12.so
3556219000-355621d000 rw-p 00000000 00:00 0
3556400000-355643b000 r-xp 00000000 08:03 51775527                       /usr/lib64/libxslt.so.1.1.26
355643b000-355663b000 ---p 0003b000 08:03 51775527                       /usr/lib64/libxslt.so.1.1.26
355663b000-355663d000 rw-p 0003b000 08:03 51775527                       /usr/lib64/libxslt.so.1.1.26
3556800000-3556883000 r-xp 00000000 08:03 1048992                        /lib64/libm-2.12.so
3556883000-3556a82000 ---p 00083000 08:03 1048992                        /lib64/libm-2.12.so
3556a82000-3556a83000 r--p 00082000 08:03 1048992                        /lib64/libm-2.12.so
3556a83000-3556a84000 rw-p 00083000 08:03 1048992                        /lib64/libm-2.12.so
3556c00000-3556c15000 r-xp 00000000 08:03 1048991                        /lib64/libz.so.1.2.3
3556c15000-3556e14000 ---p 00015000 08:03 1048991                        /lib64/libz.so.1.2.3
3556e14000-3556e15000 r--p 00014000 08:03 1048991                        /lib64/libz.so.1.2.3
3556e15000-3556e16000 rw-p 00015000 08:03 1048991                        /lib64/libz.so.1.2.3
3557000000-355701d000 r-xp 00000000 08:03 1048993                        /lib64/libselinux.so.1
355701d000-355721c000 ---p 0001d000 08:03 1048993                        /lib64/libselinux.so.1
355721c000-355721d000 r--p 0001c000 08:03 1048993                        /lib64/libselinux.so.1
355721d000-355721e000 rw-p 0001d000 08:03 1048993                        /lib64/libselinux.so.1
355721e000-355721f000 rw-p 00000000 00:00 0
3557800000-3557816000 r-xp 00000000 08:03 1048999                        /lib64/libgcc_s-4.4.7-20120601.so.1
3557816000-3557a15000 ---p 00016000 08:03 1048999                        /lib64/libgcc_s-4.4.7-20120601.so.1
3557a15000-3557a16000 rw-p 00015000 08:03 1048999                        /lib64/libgcc_s-4.4.7-20120601.so.1
3557c00000-3557c26000 r-xp 00000000 08:03 51774537                       /usr/lib64/libnssutil3.so
3557c26000-3557e25000 ---p 00026000 08:03 51774537                       /usr/lib64/libnssutil3.so
3557e25000-3557e2b000 r--p 00025000 08:03 51774537                       /usr/lib64/libnssutil3.so
3557e2b000-3557e2c000 rw-p 0002b000 08:03 51774537                       /usr/lib64/libnssutil3.so
3558000000-3558003000 r-xp 00000000 08:03 1048996                        /lib64/libplds4.so
3558003000-3558202000 ---p 00003000 08:03 1048996                        /lib64/libplds4.so
3558202000-3558203000 r--p 00002000 08:03 1048996                        /lib64/libplds4.so
3558203000-3558204000 rw-p 00003000 08:03 1048996                        /lib64/libplds4.so
3558800000-3558937000 r-xp 00000000 08:03 51777192                       /usr/lib64/libnss3.so
3558937000-3558b37000 ---p 00137000 08:03 51777192                       /usr/lib64/libnss3.so
3558b37000-3558b3c000 r--p 00137000 08:03 51777192                       /usr/lib64/libnss3.so
3558b3c000-3558b3e000 rw-p 0013c000 08:03 51777192                       /usr/lib64/libnss3.so
3558b3e000-3558b40000 rw-p 00000000 00:00 0
3558c00000-3558c04000 r-xp 00000000 08:03 1048995                        /lib64/libplc4.so
3558c04000-3558e03000 ---p 00004000 08:03 1048995                        /lib64/libplc4.so
3558e03000-3558e04000 r--p 00003000 08:03 1048995                        /lib64/libplc4.so
3558e04000-3558e05000 rw-p 00004000 08:03 1048995                        /lib64/libplc4.so
3559000000-3559039000 r-xp 00000000 08:03 1048994                        /lib64/libnspr4.so
3559039000-3559239000 ---p 00039000 08:03 1048994                        /lib64/libnspr4.so
3559239000-355923a000 r--p 00039000 08:03 1048994                        /lib64/libnspr4.so
355923a000-355923c000 rw-p 0003a000 08:03 1048994                        /lib64/libnspr4.so
355923c000-355923e000 rw-p 00000000 00:00 0
3559800000-3559807000 r-xp 00000000 08:03 1048983                        /lib64/libcrypt-2.12.so
3559807000-3559a07000 ---p 00007000 08:03 1048983                        /lib64/libcrypt-2.12.so
3559a07000-3559a08000 r--p 00007000 08:03 1048983                        /lib64/libcrypt-2.12.so
3559a08000-3559a09000 rw-p 00008000 08:03 1048983                        /lib64/libcrypt-2.12.so
3559a09000-3559a37000 rw-p 00000000 00:00 0
355a000000-355a016000 r-xp 00000000 08:03 1049006                        /lib64/libresolv-2.12.so
355a016000-355a216000 ---p 00016000 08:03 1049006                        /lib64/libresolv-2.12.so
355a216000-355a217000 r--p 00016000 08:03 1049006                        /lib64/libresolv-2.12.so
355a217000-355a218000 rw-p 00017000 08:03 1049006                        /lib64/libresolv-2.12.so
355a218000-355a21a000 rw-p 00000000 00:00 0
355bc00000-355bc02000 r-xp 00000000 08:03 1048691                        /lib64/libfreebl3.so
355bc02000-355be01000 ---p 00002000 08:03 1048691                        /lib64/libfreebl3.so
355be01000-355be02000 r--p 00001000 08:03 1048691                        /lib64/libfreebl3.so
355be02000-355be03000 rw-p 00002000 08:03 1048691                        /lib64/libfreebl3.so
355c000000-355c028000 r-xp 00000000 08:03 51777208                       /usr/lib64/libsmime3.so
355c028000-355c227000 ---p 00028000 08:03 51777208                       /usr/lib64/libsmime3.so
355c227000-355c22c000 r--p 00027000 08:03 51777208                       /usr/lib64/libsmime3.so
355c22c000-355c22d000 rw-p 0002c000 08:03 51777208                       /usr/lib64/libsmime3.so
355c400000-355c403000 r-xp 00000000 08:03 1049014                        /lib64/libcom_err.so.2.1
355c403000-355c602000 ---p 00003000 08:03 1049014                        /lib64/libcom_err.so.2.1
355c602000-355c603000 r--p 00002000 08:03 1049014                        /lib64/libcom_err.so.2.1
355c603000-355c604000 rw-p 00003000 08:03 1049014                        /lib64/libcom_err.so.2.1
355cc00000-355cc3e000 r-xp 00000000 08:03 51776068                       /usr/lib64/libssl3.so
355cc3e000-355ce3e000 ---p 0003e000 08:03 51776068                       /usr/lib64/libssl3.so
355ce3e000-355ce41000 r--p 0003e000 08:03 51776068                       /usr/lib64/libssl3.so
355ce41000-355ce42000 rw-p 00041000 08:03 51776068                       /usr/lib64/libssl3.so
355ce42000-355ce43000 rw-p 00000000 00:00 0
355d800000-355d949000 r-xp 00000000 08:03 51777201                       /usr/lib64/libxml2.so.2.7.6
355d949000-355db48000 ---p 00149000 08:03 51777201                       /usr/lib64/libxml2.so.2.7.6
355db48000-355db52000 rw-p 00148000 08:03 51777201                       /usr/lib64/libxml2.so.2.7.6
355db52000-355db53000 rw-p 00000000 00:00 0
355f800000-355f841000 r-xp 00000000 08:03 1049016                        /lib64/libgssapi_krb5.so.2.2
355f841000-355fa41000 ---p 00041000 08:03 1049016                        /lib64/libgssapi_krb5.so.2.2
355fa41000-355fa42000 r--p 00041000 08:03 1049016                        /lib64/libgssapi_krb5.so.2.2
355fa42000-355fa44000 rw-p 00042000 08:03 1049016                        /lib64/libgssapi_krb5.so.2.2
355fc00000-355fdba000 r-xp 00000000 08:03 51776092                       /usr/lib64/libcrypto.so.1.0.1e
355fdba000-355ffb9000 ---p 001ba000 08:03 51776092                       /usr/lib64/libcrypto.so.1.0.1e
355ffb9000-355ffd4000 r--p 001b9000 08:03 51776092                       /usr/lib64/libcrypto.so.1.0.1e
355ffd4000-355ffe0000 rw-p 001d4000 08:03 51776092                       /usr/lib64/libcrypto.so.1.0.1e
355ffe0000-355ffe4000 rw-p 00000000 00:00 0
3560000000-3560029000 r-xp 00000000 08:03 1049013                        /lib64/libk5crypto.so.3.1
3560029000-3560229000 ---p 00029000 08:03 1049013                        /lib64/libk5crypto.so.3.1
3560229000-356022a000 r--p 00029000 08:03 1049013                        /lib64/libk5crypto.so.3.1
356022a000-356022b000 rw-p 0002a000 08:03 1049013                        /lib64/libk5crypto.so.3.1
356022b000-356022c000 rw-p 00000000 00:00 0
3560400000-35604db000 r-xp 00000000 08:03 1049015                        /lib64/libkrb5.so.3.3
35604db000-35606db000 ---p 000db000 08:03 1049015                        /lib64/libkrb5.so.3.3
35606db000-35606e5000 r--p 000db000 08:03 1049015                        /lib64/libkrb5.so.3.3
35606e5000-35606e7000 rw-p 000e5000 08:03 1049015                        /lib64/libkrb5.so.3.3
3560800000-3560802000 r-xp 00000000 08:03 1049011                        /lib64/libkeyutils.so.1.3
3560802000-3560a01000 ---p 00002000 08:03 1049011                        /lib64/libkeyutils.so.1.3
3560a01000-3560a02000 r--p 00001000 08:03 1049011                        /lib64/libkeyutils.so.1.3
3560a02000-3560a03000 rw-p 00002000 08:03 1049011                        /lib64/libkeyutils.so.1.3
3560c00000-3560c0a000 r-xp 00000000 08:03 1049012                        /lib64/libkrb5support.so.0.1
3560c0a000-3560e09000 ---p 0000a000 08:03 1049012                        /lib64/libkrb5support.so.0.1
3560e09000-3560e0a000 r--p 00009000 08:03 1049012                        /lib64/libkrb5support.so.0.1
3560e0a000-3560e0b000 rw-p 0000a000 08:03 1049012                        /lib64/libkrb5support.so.0.1
3561000000-3561032000 r-xp 00000000 08:03 1049008                        /lib64/libidn.so.11.6.1
3561032000-3561231000 ---p 00032000 08:03 1049008                        /lib64/libidn.so.11.6.1
3561231000-3561232000 rw-p 00031000 08:03 1049008                        /lib64/libidn.so.11.6.1
3561400000-3561419000 r-xp 00000000 08:03 51776008                       /usr/lib64/libsasl2.so.2.0.23
3561419000-3561618000 ---p 00019000 08:03 51776008                       /usr/lib64/libsasl2.so.2.0.23
3561618000-3561619000 r--p 00018000 08:03 51776008                       /usr/lib64/libsasl2.so.2.0.23
3561619000-356161a000 rw-p 00019000 08:03 51776008                       /usr/lib64/libsasl2.so.2.0.23
3561800000-3561862000 r-xp 00000000 08:03 51777213                       /usr/lib64/libssl.so.1.0.1e
3561862000-3561a62000 ---p 00062000 08:03 51777213                       /usr/lib64/libssl.so.1.0.1e
3561a62000-3561a66000 r--p 00062000 08:03 51777213                       /usr/lib64/libssl.so.1.0.1e
3561a66000-3561a6d000 rw-p 00066000 08:03 51777213                       /usr/lib64/libssl.so.1.0.1e
3561c00000-3561c52000 r-xp 00000000 08:03 51777215                       /usr/lib64/libcurl.so.4.1.1
3561c52000-3561e52000 ---p 00052000 08:03 51777215                       /usr/lib64/libcurl.so.4.1.1
3561e52000-3561e55000 rw-p 00052000 08:03 51777215                       /usr/lib64/libcurl.so.4.1.1
3562000000-356200e000 r-xp 00000000 08:03 1049009                        /lib64/liblber-2.4.so.2.10.3
356200e000-356220d000 ---p 0000e000 08:03 1049009                        /lib64/liblber-2.4.so.2.10.3
356220d000-356220e000 r--p 0000d000 08:03 1049009                        /lib64/liblber-2.4.so.2.10.3
356220e000-356220f000 rw-p 0000e000 08:03 1049009                        /lib64/liblber-2.4.so.2.10.3
3562400000-3562427000 r-xp 00000000 08:03 51777214                       /usr/lib64/libssh2.so.1.0.1
3562427000-3562626000 ---p 00027000 08:03 51777214                       /usr/lib64/libssh2.so.1.0.1
3562626000-3562628000 rw-p 00026000 08:03 51777214                       /usr/lib64/libssh2.so.1.0.1
3562800000-356284d000 r-xp 00000000 08:03 1049010                        /lib64/libldap-2.4.so.2.10.3
356284d000-3562a4d000 ---p 0004d000 08:03 1049010                        /lib64/libldap-2.4.so.2.10.3
3562a4d000-3562a4f000 r--p 0004d000 08:03 1049010                        /lib64/libldap-2.4.so.2.10.3
3562a4f000-3562a51000 rw-p 0004f000 08:03 1049010                        /lib64/libldap-2.4.so.2.10.3
7fba10000000-7fba10021000 rw-p 00000000 00:00 0
7fba10021000-7fba14000000 ---p 00000000 00:00 0
7fba18000000-7fba18f50000 rw-p 00000000 00:00 0
7fba18f50000-7fba1c000000 ---p 00000000 00:00 0
7fba1c000000-7fba1d4e4000 rw-p 00000000 00:00 0
7fba1d4e4000-7fba20000000 ---p 00000000 00:00 0
7fba20000000-7fba20021000 rw-p 00000000 00:00 0
7fba20021000-7fba24000000 ---p 00000000 00:00 0
7fba24000000-7fba24021000 rw-p 00000000 00:00 0
7fba24021000-7fba28000000 ---p 00000000 00:00 0
7fba28000000-7fba28021000 rw-p 00000000 00:00 0
7fba28021000-7fba2c000000 ---p 00000000 00:00 0
7fba2db17000-7fba2db18000 ---p 00000000 00:00 0
7fba2db18000-7fba2db98000 rw-p 00000000 00:00 0
7fba2db98000-7fba2db99000 r-xp 00000000 08:03 51774183                   /usr/lib64/gconv/ISO8859-1.so
7fba2db99000-7fba2dd99000 ---p 00001000 08:03 51774183                   /usr/lib64/gconv/ISO8859-1.so
7fba2dd99000-7fba2dd9a000 r--p 00001000 08:03 51774183                   /usr/lib64/gconv/ISO8859-1.so
7fba2dd9a000-7fba2dd9b000 rw-p 00002000 08:03 51774183                   /usr/lib64/gconv/ISO8859-1.so
7fba2dd9b000-7fba2dda2000 r--s 00000000 08:03 51774250                   /usr/lib64/gconv/gconv-modules.cache
7fba2dda2000-7fba2dda3000 ---p 00000000 00:00 0
7fba2dda3000-7fba2de23000 rw-p 00000000 00:00 0
7fba2de23000-7fba2de24000 ---p 00000000 00:00 0
7fba2de24000-7fba2dea4000 rw-p 00000000 00:00 0
7fba2dea4000-7fba2dea5000 ---p 00000000 00:00 0
7fba2dea5000-7fba2df25000 rw-p 00000000 00:00 0
7fba2df25000-7fba2df26000 ---p 00000000 00:00 0
7fba2df26000-7fba2dfa6000 rw-p 00000000 00:00 0
7fba2dfa6000-7fba2dfa7000 ---p 00000000 00:00 0
7fba2dfa7000-7fba2e027000 rw-p 00000000 00:00 0
7fba2e027000-7fba2e034000 r-xp 00000000 08:03 1048608                    /lib64/libnss_files-2.12.so
7fba2e034000-7fba2e233000 ---p 0000d000 08:03 1048608                    /lib64/libnss_files-2.12.so
7fba2e233000-7fba2e234000 r--p 0000c000 08:03 1048608                    /lib64/libnss_files-2.12.so
7fba2e234000-7fba2e235000 rw-p 0000d000 08:03 1048608                    /lib64/libnss_files-2.12.so
7fba2e235000-7fba2e242000 rw-p 00000000 00:00 0
7fba2e242000-7fba2e249000 r-xp 00000000 08:03 1048987                    /lib64/librt-2.12.so
7fba2e249000-7fba2e448000 ---p 00007000 08:03 1048987                    /lib64/librt-2.12.so
7fba2e448000-7fba2e449000 r--p 00006000 08:03 1048987                    /lib64/librt-2.12.so
7fba2e449000-7fba2e44a000 rw-p 00007000 08:03 1048987                    /lib64/librt-2.12.so
7fba2e44a000-7fba2e44f000 rw-p 00000000 00:00 0
7fba2e44f000-7fba2e47b000 r-xp 00000000 08:03 51777100                   /usr/lib64/libvorbis.so.0.4.3
7fba2e47b000-7fba2e67a000 ---p 0002c000 08:03 51777100                   /usr/lib64/libvorbis.so.0.4.3
7fba2e67a000-7fba2e67b000 rw-p 0002b000 08:03 51777100                   /usr/lib64/libvorbis.so.0.4.3
7fba2e67b000-7fba2e680000 r-xp 00000000 08:03 51777091                   /usr/lib64/libogg.so.0.6.0
7fba2e680000-7fba2e880000 ---p 00005000 08:03 51777091                   /usr/lib64/libogg.so.0.6.0
7fba2e880000-7fba2e881000 rw-p 00005000 08:03 51777091                   /usr/lib64/libogg.so.0.6.0
7fba2e881000-7fba2e8b4000 r-xp 00000000 08:03 51777106                   /usr/lib64/libtheora.so.0.3.9
7fba2e8b4000-7fba2eab4000 ---p 00033000 08:03 51777106                   /usr/lib64/libtheora.so.0.3.9
7fba2eab4000-7fba2eab5000 rw-p 00033000 08:03 51777106                   /usr/lib64/libtheora.so.0.3.9
7fba2eab5000-7fba2eab6000 rw-p 00000000 00:00 0
7fba2eab6000-7fba2eace000 r-xp 00000000 08:03 51777119                   /usr/lib64/libspeex.so.1.5.0
7fba2eace000-7fba2ecce000 ---p 00018000 08:03 51777119                   /usr/lib64/libspeex.so.1.5.0
7fba2ecce000-7fba2eccf000 rw-p 00018000 08:03 51777119                   /usr/lib64/libspeex.so.1.5.0
7fba2eccf000-7fba2ecd0000 rw-p 00000000 00:00 0
7fba2ecd4000-7fba2ecd8000 rw-p 00000000 00:00 0
7fba2ecd8000-7fba2ecdc000 r-xp 00000000 08:03 1048589                    /lib64/libSegFault.so
7fba2ecdc000-7fba2eedb000 ---p 00004000 08:03 1048589                    /lib64/libSegFault.so
7fba2eedb000-7fba2eedc000 r--p 00003000 08:03 1048589                    /lib64/libSegFault.so
7fba2eedc000-7fba2eedd000 rw-p 00004000 08:03 1048589                    /lib64/libSegFault.so
7fba2eedd000-7fba2eede000 rw-p 00000000 00:00 0
7ffd48a8a000-7ffd48a9f000 rw-p 00000000 00:00 0                          [stack]
7ffd48ab0000-7ffd48ab1000 r-xp 00000000 00:00 0                          [vdso]
ffffffffff600000-ffffffffff601000 r-xp 00000000 00:00 0                  [vsyscall]

**Comment by karlheyes** [comment]
Can you verify that you are using the latest release from the distro of openssl etc?

If so, can you replicate the issue by just running the build in isolation (relaying streams should not change things if needed). And then hit the system with multiple download requests like 

curl -o /dev/null -H 'icy-metadata:1' -s -k https://...../....

I don't know if your usage is mostly time limited or mostly web pages being ssl while streams non-ssl. If we can get a usage pattern to trigger without outages then great.  The stacktrace was not useful there which indicates some stack corruption.  A bad memory reference within libcurl etc could be resolved in a later update but I would want to see if corruption is triggered elsewhere.

karl.

**Comment by djamps** [comment]
FYI SSL usage is 100% client connections to mount points.   The web pages / stats are all non-SSL with some non-SSL streaming in the mix.

**Comment by ibcs01** [comment]
Good evening everyone. Nice to see some activity here :) The situation is almost the same on this side. The input sources are streaming non-SSL. All clients listen via SSL. Icecast keeps crashing with the error 4 in libcrypto.so. We are now using a workaround that start Icecast again automatically if it crashes, but it is far from stable. But this is not the best solution as you can imagine.

**Comment by ibcs01** [comment]
Just to give you an idea, the latest crash was yesterday:

root@server:/srv/www# service icecast status
● icecast.service - Icecast server
   Loaded: loaded (/lib/systemd/system/icecast.service; enabled)
   Active: active (running) since Thu 2016-12-08 19:09:25 CET; 1 day 3h ago
  Process: 13785 ExecStop=/bin/kill $MAINPID (code=exited, status=1/FAILURE)
  Process: 13793 ExecStart=/usr/local/bin/icecast -b -c /usr/local/etc/icecast.xml (code=exited, status=0/SUCCESS)
 Main PID: 13794 (icecast)
   CGroup: /system.slice/icecast.service
           └─13794 /usr/local/bin/icecast -b -c /usr/local/etc/icecast.xml

**Comment by djamps** [comment]
I enabled debug logging for the next crash.  We are getting several crashes per day (usually triggers once there are >400 connections) so it shouldn't be hard to get useful info if I prep things correctly.  Core dumps should be enabled at this point, but is there any compile flags that would help?

**Comment by karlheyes** [comment]
"make clean debug" in general is best, you could also run something before starting icecast

export MALLOC_CHECK_=2 
icecast ....

valgrind is usually good but with SSL will produce lots of false information.  If you have a late enough gcc version you could add a flag 'make CFLAGS="-g -fstack-protector-strong'  instead of make debug

karl.

**Comment by djamps** [comment]
Although I haven't had a crash with the debug build yet, the issue we had on ubuntu has now resurfaced on CentOS.    Trying to connect to an SSL streams suddenly becomes impossible (time out in all new player connections).   In the debug error.log you will see lots of these at the same time:
connection/connection_read_ssl error 1, error:1408A10B:SSL routines:SSL3_GET_CLIENT_HELLO:wrong version number
connection/connection_read_ssl error 1, error:1408A10B:SSL routines:SSL3_GET_CLIENT_HELLO:wrong version number
connection/connection_read_ssl error 1, error:140A1175:SSL routines:SSL_BYTES_TO_CIPHER_LIST:inappropriate fallback

And so on...

**Comment by djamps** [comment]
I suspect, but not sure of yet, that there could have been some CPU/memory issues that for some reason only triggered under heavy SSL load.   Replaced the physical hardware and so far haven't had a crash under moderate load today.   Will update in in a day or two with the final results.

**Comment by djamps** [comment]
OK guys/gals I've managed to resolve the segfault issue by replacing the hardware.  In fact, the replacement hardware is an identical unit.   My suspicion is that this particular segfault is most likely being caused by faulty hardware.

**Comment by djamps** [comment]
Deleted last comment as just when I typed it I got this:
icecast: *** Error in `/usr/local/bin/icecast': double free or corruption (!prev): 0x00007fd0bcef36f0 ***

**Comment by karlheyes** [comment]
strange how bugs manifest themselves just after you think they are resolved.

I presume you got a core dump identifying the full stacktrace as that particular message is actually from glibc. Can you also identify what was occurring at the time of the crash report.

karl.

**Comment by djamps** [comment]
I did not have debug build or core dumps enabled for the double free.   They should be enabled now along with 'CFLAGS="-g -fstack-protector-strong'.   The only thing that happened on or around the time of the crash was a hostname change via hostnamectl (centos7).

**Comment by djamps** [comment]
Unfortunately not so good news.   After complete hardware swaps (completely different CPU, mainboards, everything) and even trying many different operating systems / OpenSSL versions, we are unable to achieve stable SSL operation.   Segfaults are occuring every few days on multiple nodes without fail.   To make matters worse, so far we are unable to get a core dump on any OS.   At this point we've steered traffic away from the SSL ports and things are again stable.   Hopefully someone else can help/chime in but I don't think there's much else I can do here to help.   Hopefully SSL operation can be fixed one day because as we all know everything is being forced more and more to SSL-only.

**Comment by karlheyes** [comment]
is 1.0.1f the latest openssl you have available to you?  I've noticed the 1.0 series are now out of support. Just wondering if there is some crafted ssl attack going on that causes a crash.  As for why a core dump is not occurring, I don't know, assuming cores can be wrtten to file as configured in the /proc tree then there should be no reason for that not to occur.

karl.

**Comment by djamps** [comment]
Tried so far - 
1.0.1e-fips (CentOS6 and CentOS7) 
1.0.1f  (Ubuntu 14 LTS)

Unfortunately there aren't many other options as the major OS vendors seem to be sticking to 1.0.1.

**Comment by djamps** [comment]
I am happy to report Karl has found/fixed the issue at least in our case.   Thanks again Karl.

**Comment by ibcs01** [comment]
Great news, will check it out tomorrow!
I will keep you posted...

**Comment by ibcs01** [comment]
Running fine now for about one week without any crashes!
Thanks a lot Karl. You are my hero :)

This issue is now resolved and can be closed.
