### ISSUE TITLE
Duration in log files is reported as 18446744073709551615

### ISSUE THREAD

**Issue by als2002** [karlheyes/icecast-kh#146]
Hi!
Server - Debian 8.6 (Jessie) 3.16.0-4-amd64, Icecast 2.4.0-kh3-20161120011351.
While it does not matter for no-sound urls, for "GET /Stream_23.aac" it is a little bit confusing...
(seems to be -1 as 64 bit unsigned ... )

**grep 18446744073709551615 access.log**
87.110.211.112 - - [29/Dec/2016:10:46:45 +0200] "GET /ehr64.m3u HTTP/1.1" 200 135 "-" "Streamripper/1.x" 18446744073709551615
87.110.211.112 - - [29/Dec/2016:10:47:05 +0200] "GET /ehr64.m3u HTTP/1.1" 200 135 "-" "Streamripper/1.x" 18446744073709551615
87.110.211.112 - - [29/Dec/2016:10:49:42 +0200] "GET /ehr64.m3u HTTP/1.1" 200 135 "-" "Streamripper/1.x" 18446744073709551615
**80.89.76.108 - - [29/Dec/2016:11:50:31 +0200] "GET /Stream_23.aac HTTP/1.1" 200 373 "-" "AppleCoreMedia/1.0.0.14B100 (iPhone; U; CPU OS 10_1_1 like Mac OS X; en_us)" 18446744073709551615**
91.237.98.22 - - [29/Dec/2016:12:02:42 +0200] "GET /status-json.xsl HTTP/1.0" 404 119 "-" "-" 18446744073709551615
87.110.211.112 - - [29/Dec/2016:12:48:26 +0200] "GET /ehr64.m3u HTTP/1.1" 200 135 "-" "Streamripper/1.x" 18446744073709551615
87.110.211.112 - - [29/Dec/2016:12:48:42 +0200] "GET /ehr64.m3u HTTP/1.1" 200 135 "-" "Streamripper/1.x" 18446744073709551615
80.89.78.233 - - [29/Dec/2016:12:55:49 +0200] "GET /ehr.mp3.m3u HTTP/1.1" 200 137 "-" "MTA:SA Server 194.19.245.85:22003 - See http://mtasa.com/agent/" 18446744073709551615
159.148.153.180 - - [29/Dec/2016:13:04:01 +0200] "GET /admin/stats.xml?mount=/sfm_src_1 HTTP/1.1" 401 121 "-" "Wget/1.16 (linux-gnu)" 18446744073709551615
91.105.127.186 - - [29/Dec/2016:13:15:33 +0200] "GET /ehr.mp3.m3u HTTP/1.1" 200 137 "-" "MTA:SA Server 194.19.245.85:22003 - See http://mtasa.com/agent/" 18446744073709551615
80.89.74.245 - - [29/Dec/2016:13:16:14 +0200] "GET /ehr.mp3.m3u HTTP/1.1" 200 137 "-" "MTA:SA Server 194.19.245.85:22003 - See http://mtasa.com/agent/" 18446744073709551615

**Comment by karlheyes** [comment]
yes, a bit suspicious.  I suspect the clock is getting changed (eg ntp) and it's just near a second boundary.  so a short duration like 5ms may be looking like -2ms in effect. As the times are just based in seconds then -1 may be the final result.  I'll add a comparison for that case in the logging code to make sure.

karl.

**Comment by als2002** [comment]
On 2017.01.02. 20:40, Karl Heyes wrote:
>
> yes, a bit suspicious. I suspect the clock is getting changed (eg ntp) 
> and it's just near a second boundary. so a short duration like 5ms may 
> be looking like -2ms in effect. As the times are just based in seconds 
> then -1 may be the final result. I'll add a comparison for that case 
> in the logging code to make sure.
>
Yes, it looks like this... NTPd is running on this server...

some stats form 4h log:
#grep -c . access.log.20170104_140236
63943
# grep -c 1844674407370955161 access.log.20170104_140236
17
mainly :
87.110.211.112 - - [04/Jan/2017:11:50:30 +0200] "GET /ehr64.m3u 
HTTP/1.1" 200 135 "-" "Streamripper/1.x" 18446744073709551615
87.110.211.112 - - [04/Jan/2017:11:53:54 +0200] "GET /ehr64.m3u 
HTTP/1.1" 200 135 "-" "Streamripper/1.x" 18446744073709551615
87.110.211.112 - - [04/Jan/2017:12:49:15 +0200] "GET /ehr64.m3u 
HTTP/1.1" 200 135 "-" "Streamripper/1.x" 18446744073709551615
87.110.211.112 - - [04/Jan/2017:12:49:43 +0200] "GET /ehr64.m3u 
HTTP/1.1" 200 135 "-" "Streamripper/1.x" 18446744073709551615


Best regards,
Alexander

**Comment by karlheyes** [comment]
check added in master tree

karl
