### ISSUE TITLE
Move slow listener to another mountpoint

### ISSUE THREAD

**Issue by andrefilimono** [karlheyes/icecast-kh#147]
Hi!
I have some mountpoints with different bitrate (64, 128 and etc).
Is it possible to find "slow" listeners (as I understand it, "slow" listeners have a high "lag" value) and move them to another mountpoint with a lower bitrate?
Or maybe something like an adaptive bitrate already implemented in icecast-kh?

**Comment by romainwn** [comment]
Hi, did you find a solution to your problem ? If so, this might be interesting to share it with us :)
