### ISSUE TITLE
client/worker_wait stuck for > 10 seconds

### ISSUE THREAD

**Issue by markymarrow** [karlheyes/icecast-kh#150]
I've no idea what this really means (other than something took longer than expected):
  `WARN client/worker_wait worker 0x2194000 has been stuck for 17973 ms`
but we have a server giving messages like these and they're generally proceeded by a rash of
  `source/source_read Disconnecting /<mount> due to socket timeout`
a number of which are localhost sourced relays fed from ezstream - so it shouldn't be a network issue

What can I do to shed some more light on what is happening here
[server is running on CentOS6 x64]

**Comment by karlheyes** [comment]
The clients on the worker in question took that amount of time to complete. As that is nearly 18second then I'm not surprised a selection of other clients timed out.  Now the question to as why is occurred is difficult to idientify based on the current information but I've only seen it when adswizz is involved (it seems to stall some calls when they should not stall).  There is only one other case that can delay things, very large xml lists but 18 seconds is still a large number for that.   An overloaded machine may have some bearing but again, 18 seconds is a lot, so you would have the same message cropping up for any number larger than 3 IIRC.

Just make sure you have an adequate number of <workers> for your setup, ie not 1 worker for 40000 clients. should be in line with the cores you have or want to use.

karl.

**Comment by markymarrow** [comment]
adswizz, not using that
large xml lists, not sure - presumably you're not talking about the config xml, the only other thing I'm doing with xml is gathering stats from the admin interface every minute (which is a flurry of calls, one per source, 100 sources)
Server isn't overloaded, LA 0.1 (icecast runs at around 3% CPU 2% Mem)

I've around 500 clients on the box & it has 8 cores (4/8T)
Ok, so I hadn't spotted that I could specify the number of workers (I've been hanging around on 2.3.2-kh30 for a long time), guess it defaults to just the one - I've reconfigured for 8 (possibly overkill?) & will see how that goes.

Thanks.

**Comment by als2002** [comment]
Hi! 
I have encountered very similar situation recently... Server has running flawlessly for a long time (except fallback issue, he-he). 
There were worker stuck warnings roughly once per hour, with stuck time about one second, that seemed to be harmless. Then, yesterday, suddenly listeners started to report gaps in playback, and even disconnects. 
Error log started to be saturated with stuck warning, which ended up with them being issued nearly every second.
[2017-03-08  22:11:03] WARN client/worker_wait worker 0x89b090 has been stuck for 2264 ms
[2017-03-08  22:11:07] WARN client/worker_wait worker 0x89b2b0 has been stuck for 1095 ms
[2017-03-08  22:11:27] WARN client/worker_wait worker 0x82bc20 has been stuck for 1176 ms
[2017-03-08  22:11:45] WARN client/worker_wait worker 0x89b2b0 has been stuck for 2212 ms

I stopped all other services, so server ( HP hardware ) was nearly idle. Still no luck. 
Will not describe all steps, but problem was solved by moving icecast log location from SATA hard drive to SAS raid. There were no obvious problems with SATA drive (smart, visible delays, system logs, etc.). Seems, that icecast is sensitive to delays in writing log entries. ( this page helped me a lot http://www.chileoffshore.com/en/interesting-articles/126-linux-wait-io-problem )

Maybe this experience will be helpful.
Alexander

**Comment by markymarrow** [comment]
I was very sceptical about your suggestion, I fired up vmstat & sat watching the wait column - mostly 0, the occasional 1...

Then suddenly there's a 12 second burst of 10-50% wait (journal flush) & a number of 'been stuck' log messages appear.

I can't say I agree with your links suggestion of removing the journal, however -
changing the io scheduler on that disk (Raid-1 ssd) to deadline, helped a little
changing the journal commit interval to 30 helps a lot (not that good an idea though)
moving the logs to /dev/shm (ram disk - I do have plenty of spare ram in this box) makes the issue go away, the logs are useful for debugging but I don't need to keep them around.

Karl - is there merit in adjusting the way logging works? as in a separate thread to do the actual writing? (and I say this without having looked at what happens currently)

**Comment by als2002** [comment]
Well, at least You now located the problem.
My link was more about one-liner to determine process, that is causing io stop, not recipes to solve it :-)

**Comment by karlheyes** [comment]
Can you try the latest master branch code to see how that works out.  The latest commit extends on something already present to act as a buffer for a separate thread for logging.

The code seems to be stable and extends across all logs. You should not get any sort of stall in such cases now.

karl

**Comment by karlheyes** [comment]
fixed another issue in the log changes, may need to retry the master branch again.

karl.

**Comment by markymarrow** [comment]
I'm getting a segfault on startup when trying the latest master...

```
...
[2017-03-27  14:38:58] DBUG stats/modify_node_event update "global" banned_IPs (0)
[2017-03-27  14:38:58] DBUG stats/modify_node_event update "global" clients (2)
[2017-03-27  14:38:58] DBUG stats/modify_node_event update "global" outgoing_kbitrate (0)
[2017-03-27  14:38:58] INFO client/log_commit_thread started
```

**Comment by karlheyes** [comment]
any chance of running that in a gdb session, seems to be ok here but I don't know what settings you have configured, and what the platforms specifics are.  Seems odd that those other stats are appearing before
the commit thread message.

karl

**Comment by markymarrow** [comment]
Here's a gdb run
```
(gdb) run -c icecast.xml
Starting program: /home/admin/kh-git/icecast-kh/src/icecast -c icecast.xml
[Thread debugging using libthread_db enabled]
Changed supplementary groups based on user: admin.
Changed groupid to 506.
Changed userid to 506.
[New Thread 0x40200940 (LWP 25706)]

Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x40200940 (LWP 25706)]
do_log_run (log_id=2) at log.c:413
413	        next = loglist [log_id].written_entry->next;
(gdb) print log_id
$3 = 2
(gdb) print loglist [log_id].written_entry
$4 = (log_entry_t *) 0x707267702c33313d
(gdb) print loglist [log_id].written_entry->next
Cannot access memory at address 0x707267702c33313d
```

**Comment by karlheyes** [comment]
how about

print loglist [log_id]
print *loglist [log_id].written_entry

karl

**Comment by markymarrow** [comment]
```
(gdb) print loglist [log_id]
$1 = {in_use = 1, level = 4, filename = 0x6761e0 "/var/log/icecast/access.log", logfile = 0x675fa0, size = 47802, trigger_level = 1024000000, reopen_at = 0, duration = 0, 
  archive_timestamp = -1, total = 0, entries = 0, keep_entries = 100, written_entry = 0x707267702c33313d, log_head = 0x0, log_tail = 0x0, buffer = 0x0}
(gdb) print *loglist [log_id].written_entry
Cannot access memory at address 0x707267702c33313d
```

**Comment by karlheyes** [comment]
ok, dumb uninitialised bug fixed.  That should be ok now

karl.
