### ISSUE TITLE
Icecast-kh3 continues to run as Background Service

### ISSUE THREAD

**Issue by JAR101** [karlheyes/icecast-kh#154]
Icecast-kh3 continues to run as a service in the background.  Even when shut down. (It will startup automatically.)

The service should be set to "Stopped" in the service tab (mscongfig) otherwise you cannot create a socket on the port.

**Comment by karlheyes** [comment]
kh5 is now uploaded.  I've been trying it as a service and it seems to be working as intended, however if there is some quirk in the usage that affects your setup differently then let me know.

karl.

**Comment by JAR101** [comment]
Excellent!  Karl, thank you for the update!  Works fine.
