### ISSUE TITLE
Unable to access ssl certificates only accessible by root

### ISSUE THREAD

**Issue by leonardder** [karlheyes/icecast-kh#158]
Browsers such as NGinX and Apache as well as Dovecot and Postfix are able to access ssl certificates only readable by root, since they either have a process running as root, or they degrade privileges after loading the ssl certificates. With Icecast, neither is the case. This means that you need to have an ssl-private key which is readable by the user running icecast. This also means that you have to do additional tweaks to have lets encrypt certificates renew automatically, since Icecast can't access the default certbot/lets encrypt certificate store, since it is root access only.

Would it be possible to change the owner of the icecast process after, and not before, ssl initialization?

**Comment by karlheyes** [comment]
My recent commits should now deal with this. The SSL file reading is done at the same time as the listener socket setup so should have root reading capability in such configurations.  Obviously on reload, in such case, those files would not be readable so you won't get any changes but you will still be using the original loaded SSL certificates.

karl

**Comment by karlheyes** [comment]
can you confirm kh6 allows for this as expected?

**Comment by leonardder** [comment]
I'm now using this on two systems and it works like a charm. Closing this.
