### ISSUE TITLE
cant make kh5 src on raspberry

### ISSUE THREAD

**Issue by aresstokrat** [karlheyes/icecast-kh#160]
Hello! Im sorry, maybe its my problem only, but i cant make kh5

> ~/icecast-kh-icecast-2.4.0-kh5 $ make
> GIT_VERSION=20170516172431
> make  all-recursive
> make[1]: вход в каталог «/home/pi/icecast-kh-icecast-2.4.0-kh5»
> Making all in conf
> make[2]: вход в каталог «/home/pi/icecast-kh-icecast-2.4.0-kh5/conf»
> sed -e 's,@pkgdatadir\@,/usr/local/share/icecast,g' -e 's,@localstatedir\@,/usr/local/var,g' -e 's,@PACKAGE\@,icecast,g' ./icecast.xml.in > icecast.xml.dist
> sed -e 's,@pkgdatadir\@,/usr/local/share/icecast,g' -e 's,@localstatedir\@,/usr/local/var,g' -e 's,@PACKAGE\@,icecast,g' ./icecast_minimal.xml.in > icecast_minimal.xml.dist
> sed -e 's,@pkgdatadir\@,/usr/local/share/icecast,g' -e 's,@localstatedir\@,/usr/local/var,g' -e 's,@PACKAGE\@,icecast,g' ./icecast_shoutcast_compat.xml.in > icecast_shoutcast_compat.xml.dist
> make[2]: выход из каталога «/home/pi/icecast-kh-icecast-2.4.0-kh5/conf»
> Making all in doc
> make[2]: вход в каталог «/home/pi/icecast-kh-icecast-2.4.0-kh5/doc»
> make[2]: Цель «all» не требует выполнения команд.
> make[2]: выход из каталога «/home/pi/icecast-kh-icecast-2.4.0-kh5/doc»
> Making all in web
> make[2]: вход в каталог «/home/pi/icecast-kh-icecast-2.4.0-kh5/web»
> Making all in images
> make[3]: вход в каталог «/home/pi/icecast-kh-icecast-2.4.0-kh5/web/images»
> make[3]: Цель «all» не требует выполнения команд.
> make[3]: выход из каталога «/home/pi/icecast-kh-icecast-2.4.0-kh5/web/images»
> make[3]: вход в каталог «/home/pi/icecast-kh-icecast-2.4.0-kh5/web»
> make[3]: Цель «all-am» не требует выполнения команд.
> make[3]: выход из каталога «/home/pi/icecast-kh-icecast-2.4.0-kh5/web»
> make[2]: выход из каталога «/home/pi/icecast-kh-icecast-2.4.0-kh5/web»
> Making all in admin
> make[2]: вход в каталог «/home/pi/icecast-kh-icecast-2.4.0-kh5/admin»
> make[2]: Цель «all» не требует выполнения команд.
> make[2]: выход из каталога «/home/pi/icecast-kh-icecast-2.4.0-kh5/admin»
> Making all in src
> make[2]: вход в каталог «/home/pi/icecast-kh-icecast-2.4.0-kh5/src»
> Making all in avl
> make[3]: вход в каталог «/home/pi/icecast-kh-icecast-2.4.0-kh5/src/avl»
>   CC       libiceavl_la-avl.lo
>   CCLD     libiceavl.la
> make[3]: выход из каталога «/home/pi/icecast-kh-icecast-2.4.0-kh5/src/avl»
> Making all in thread
> make[3]: вход в каталог «/home/pi/icecast-kh-icecast-2.4.0-kh5/src/thread»
>   CC       libicethread_la-thread.lo
>   CCLD     libicethread.la
> make[3]: выход из каталога «/home/pi/icecast-kh-icecast-2.4.0-kh5/src/thread»
> Making all in httpp
> make[3]: вход в каталог «/home/pi/icecast-kh-icecast-2.4.0-kh5/src/httpp»
>   CC       libicehttpp_la-httpp.lo
>   CCLD     libicehttpp.la
> make[3]: выход из каталога «/home/pi/icecast-kh-icecast-2.4.0-kh5/src/httpp»
> Making all in net
> make[3]: вход в каталог «/home/pi/icecast-kh-icecast-2.4.0-kh5/src/net»
>   CC       libicenet_la-sock.lo
>   CC       libicenet_la-resolver.lo
>   CCLD     libicenet.la
> make[3]: выход из каталога «/home/pi/icecast-kh-icecast-2.4.0-kh5/src/net»
> Making all in log
> make[3]: вход в каталог «/home/pi/icecast-kh-icecast-2.4.0-kh5/src/log»
>   CC       log.lo
>   CCLD     libicelog.la
> make[3]: выход из каталога «/home/pi/icecast-kh-icecast-2.4.0-kh5/src/log»
> Making all in timing
> make[3]: вход в каталог «/home/pi/icecast-kh-icecast-2.4.0-kh5/src/timing»
>   CC       libicetiming_la-timing.lo
>   CCLD     libicetiming.la
> make[3]: выход из каталога «/home/pi/icecast-kh-icecast-2.4.0-kh5/src/timing»
> make[3]: вход в каталог «/home/pi/icecast-kh-icecast-2.4.0-kh5/src»
>   CC       cfgfile.o
> cfgfile.c: In function ‘config_clear’:
> cfgfile.c:366:9: warning: unused variable ‘i’ [-Wunused-variable]
>      int i;
>          ^
>   CC       main.o
>   CC       logging.o
>   CC       sighandler.o
>   CC       connection.o
> connection.c: In function ‘http_client_request’:
> connection.c:1093:84: error: ‘connection_t’ has no member named ‘ssl’
>                  client->schedule_ms = client->worker->time_ms + (client->connection.ssl ? 55 : 30);
>                                                                                     ^
> Makefile:593: ошибка выполнения рецепта для цели «connection.o»
> make[3]: *** [connection.o] Ошибка 1
> make[3]: выход из каталога «/home/pi/icecast-kh-icecast-2.4.0-kh5/src»
> Makefile:626: ошибка выполнения рецепта для цели «all-recursive»
> make[2]: *** [all-recursive] Ошибка 1
> make[2]: выход из каталога «/home/pi/icecast-kh-icecast-2.4.0-kh5/src»
> Makefile:512: ошибка выполнения рецепта для цели «all-recursive»
> make[1]: *** [all-recursive] Ошибка 1
> make[1]: выход из каталога «/home/pi/icecast-kh-icecast-2.4.0-kh5»
> Makefile:423: ошибка выполнения рецепта для цели «all»
> make: *** [all] Ошибка 2

**Comment by karlheyes** [comment]
Can you either apply the latest commit from master or download the latest tarball from the github (below). The error is down to an assumption of openssl being installed which is now fixed.

build with fix in is 

https://github.com/karlheyes/icecast-kh/archive/master.zip

karl.

**Comment by aresstokrat** [comment]
thank you so much for your work!
