### ISSUE TITLE
Icecast 2.4.0 KH5

### ISSUE THREAD

**Issue by ANSASERVERS** [karlheyes/icecast-kh#163]
Hey Guys,

We have just installed the latest Icecast 2.4.0 KH5 on our centova server. The server starts fine, we can mount a stream without an issue but when we go to try and open the stream in any external player it does not open the file. I have tried in itunes and VLC

Any idea?

**Comment by ANSASERVERS** [comment]
Here is the server: http://103.243.239.111:8000

**Comment by karlheyes** [comment]
indeed, my vlc has problems as well. From the vlc messages it would indicate that the aac decoder in vlc does not switch over to the mpeg decoder.  Maybe you should name your mountpoint without .aac if it is not an aac stream.

karl.

**Comment by ANSASERVERS** [comment]
HI Karl,

Let me try that quickly...

My other streams all have .aac and they are a mix of MP3 and AAC

Here is the link for that server: http://ic.phazern.com.au:8000

**Comment by ANSASERVERS** [comment]
That does seem to have done the trick. When i looked at the other server they are all AAC
