### ISSUE TITLE
configure: SSL disabled! on Centos 7

### ISSUE THREAD

**Issue by edinsof** [karlheyes/icecast-kh#164]
Hi.
I am trying to install icecast kh with SSL on Centos 7 using the following command: 
`./configure --with-openssl`

But i get this error on log: 
`configure: SSL disabled!`

openssl is installed 
```
[root@server kh]# openssl version
OpenSSL 1.0.2l  25 May 2017
```
Icecast Kh version
`2.4.0-kh5`

how can fix it ?

**Comment by edinsof** [comment]
Solved running:

```
./configure --with-openssl=/usr/local/ssl
make LIBS="-lcrypto"
make install LIBS="-lcrypto"
```

**Comment by karlheyes** [comment]
glad you resolved it. What should be happening is that the configure runs a pkg-config to check for the dependencies but if those are not in the default search paths then the new path needs to be specified. It looks like you using a brute force approach so ok. I suspect what you need to do in future is

export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/usr/local/ssl/pkgconfig

or something similar, depending on the particular installation of openssl.  The configure should then pick up the paths required.

karl
