### ISSUE TITLE
logsize not heeded in kh5 and current commit

### ISSUE THREAD

**Issue by larserne** [karlheyes/icecast-kh#168]
Works fine in kh4

**Comment by karlheyes** [comment]
Is this still an issue in the latest master work?

karl.

**Comment by Evervision** [comment]
We are also experiencing this issue with the 32-bit KH5 release on windows.

Is there any special requirements for the windows build?

**Comment by karlheyes** [comment]
I think this is now fixed in the current master, my previous fix was just a hack but should be much better now.  I'll cut a kh6 shortly.

karl.

**Comment by karlheyes** [comment]
kh6 is now out. That should now fix this issue

karl.

**Comment by waster** [comment]
Thanks! It works now.
