### ISSUE TITLE
Skip intro audio

### ISSUE THREAD

**Issue by DuncanFairley** [karlheyes/icecast-kh#169]
Is there any way I can skip playing intro audio for a client with listener_add? 
My use case is for when a client drops connection and reconnects immediately, they shouldn't have to listen to the intro audio again.

**Comment by karlheyes** [comment]
I've added an intro-skip-replay option in kh9 but this is for intro files.  It could be extended to include content from auth but you should really avoid it within the auth server to avoid sending the content in the first place.

karl

**Comment by DuncanFairley** [comment]
Forgot to mention that this accomplishes what I needed.
Thanks!
