### ISSUE TITLE
String truncation in access log

### ISSUE THREAD

**Issue by robincalmegard** [karlheyes/icecast-kh#177]
Starting with 2.3.2-kh31, icecast-kh is reporting query arguments to the access log which is great. I do however have a question regarding the string truncation being made. The limit was originally 127 characters, then it was raised to 255 characters. Is it possible to raise this limit even further, maybe in the configuration file?

We send some important data from our players in query strings. They are later parsed using a statistics tool, but we cannot currently parse all necessary data as they are truncated in the access log.

**Comment by karlheyes** [comment]
hmm, not exactly straightforward.  The log subsystem allows upto 1024 for the whole line, a legacy thing, and the part you want is a section of that, which is only limited (with 255) by the size of one of the buffers.   You would have to change 2 numbers in logging.c

in logging_access_id()
look for 
char reqbuf[....]       // change the number in there
then a few lines further down 
snprintf (reqbuf, sizeof(reqbuf), "%.10s %.235.......
change the 235 to the same number less 20.
then rebuild

To make it a config option is a bit more involved, but could be a macro setting without much trouble.

karl.

**Comment by robincalmegard** [comment]
Thank you Karl, helps a lot!
