### ISSUE TITLE
user agent deny

### ISSUE THREAD

**Issue by edinsof** [karlheyes/icecast-kh#179]
Hello
I am receiving multiple attacks to my streaming with the user agent:

> 1.1.1.1- - [12/Sep/2017:01:45:24 -0400] "POST /stream HTTP/1.1" 501 32 "-" "Mozilla/4.0 (compatible; MSIE 6.0; MSIE 5.5; Windows NT 5.0) Opera 7.02 Bork-edition [en]" 0

as it can block in my configuration and icecast?

the attack comes from multiple IPs around the world

I have tried but dont works

`<deny-agents>/path/to/file-with-useragents</deny-agents>`

my deny-agent file:

> Mozilla/4.0 (compatible; MSIE 6.0; MSIE 5.5; Windows NT 5.0) Opera 7.02 Bork-edition [en]

**Comment by karlheyes** [comment]
Check the log to see that the file is being read.  You should be able to use wildcards in there as well.

karl.
