### ISSUE TITLE
[FEATURE] url auth options for passing client headers to auth service

### ISSUE THREAD

**Issue by spr0cketeer** [karlheyes/icecast-kh#186]
Hi Karl,

The Xiph official release has these additional url auth options:

http://icecast.org/docs/icecast-2.4.0/auth.html

headers
    This is a list of HTTP headers provided by the client which should be passed to the authencation service. Those headers are prepended by the value of header_prefix and sent as POST parameters.
header_prefix
    This is the prefix used for passing client headers. 

Do you plan to incorporate them in the kh branch?

Thanks.

**Comment by karlheyes** [comment]
hmm, I suppose this would be useful for cookies or similar entries.  I think it would be best to pre-null the header list at the initial stage (with a count) rather than per-client auth, saves a little processing and avoid the memory leak from the strdup.

karl.

**Comment by spr0cketeer** [comment]
Yeah passing the client cookies to the auth service is my use case.

The examples in the docs use "ClientHeader." as header_prefix value which seems as good as any for a default.

> I think it would be best to pre-null the header list at the initial stage (with a count) rather than per-client auth

I'm a bit lost!  As I mentioned in the PR I don't know C but I could give it a go with a bit of guidance so would you mind explaining this a bit more -  by initial stage you mean when the mount is parsed in the cfg file or when a client connection is made or...?  And count?

**Comment by karlheyes** [comment]
based on the patch, I've reworked it to handle the cases I mentioned.  It is best not to keep doing the same work for each client if possible, ie the dup/nullify the list when there is no difference for any of the clients, so do that in the initial auth section, but as you have nul's in the string then it's best to have a simple count to know how many headers there are to check for.

see if the attached works for you
[auth_url.patch.txt](https://github.com/karlheyes/icecast-kh/files/1425637/auth_url.patch.txt)

**Comment by karlheyes** [comment]
there is a minor fix to that patch for the prefix override.

karl

**Comment by spr0cketeer** [comment]
Thanks for taking this on  - tried your patch out and it works great :+1: Not sure if you meant to add a link to the revised patch in your last comment, but I managed to work out a fix by changing line 111 to `url_info->header_chk_prefix = strdup (options->value);` to get the prefix override working.

**Comment by spr0cketeer** [comment]
Added in: https://github.com/karlheyes/icecast-kh/commit/508bb2e488769bd01005c78e23672e4891ec64fd
