### ISSUE TITLE
External log rotation and reopen logs doesn’t work

### ISSUE THREAD

**Issue by ncDevel** [karlheyes/icecast-kh#189]
Hello Karl

since the last major changes to the logging system the log rotation controlled by external tools is not working anymore. After renaming a log file and sending a SIGHUP or calling the admin function `/admin/function?perform=reopenlog` no new log file is opened. The logging continues to the old file.

Here’s a little fast and dirty patch:

```diff
diff --git a/src/log/log.c b/src/log/log.c
index 3c24953..3a32431 100644
--- a/src/log/log.c
+++ b/src/log/log.c
@@ -62,6 +62,7 @@
     time_t reopen_at;
     unsigned int duration;
     int archive_timestamp;
+    int force_reopen;
 
     unsigned long buffer_bytes;
     unsigned int entries;
@@ -90,6 +91,7 @@
 
     /* check for cases where an open of the logfile is wanted */
     if (loglist [id] . logfile == NULL || 
+       (loglist [id] . force_reopen) ||
        (loglist [id] . duration && loglist [id] . reopen_at <= now) ||
        (loglist [id] . trigger_level && loglist [id] . size > loglist [id] . trigger_level))
     {
@@ -98,7 +100,7 @@
             FILE *f = NULL;
             struct stat st;
 
-            if (loglist [id].logfile && loglist [id].logfile != stderr)
+            if (loglist [id].logfile && loglist [id].logfile != stderr && loglist [id].force_reopen < 1)
             {
                 char new_name [4096];
                 fclose (loglist [id] . logfile);
@@ -121,6 +123,7 @@
                 rename (loglist [id] . filename, new_name);
             }
             f = fopen (loglist [id] . filename, "a");
+            loglist [id] . force_reopen = 0;
             if (f == NULL)
             {
                 loglist [id] . logfile = stderr;
@@ -335,6 +338,7 @@
     if (loglist [log_id] . filename && loglist [log_id] . logfile)
     {
         loglist [log_id].reopen_at = (time_t)0;
+        loglist [log_id].force_reopen = 1;
     }
     _unlock_logger();
 }
```

But I’m pretty sure that you’ve a better idea to solve this problem.

Best regards
Martin

**Comment by karlheyes** [comment]
how does this work instead?

```
diff --git a/src/log/log.c b/src/log/log.c
index 3c24953..05315e1 100644
--- a/src/log/log.c
+++ b/src/log/log.c
@@ -334,7 +334,7 @@ void log_reopen(int log_id)
     _lock_logger();
     if (loglist [log_id] . filename && loglist [log_id] . logfile)
     {
-        loglist [log_id].reopen_at = (time_t)0;
+        loglist [log_id].size = loglist [log_id].trigger_level+1;
     }
     _unlock_logger();
 }

**Comment by edinsof** [comment]
In the last days after updating icecast kh I have the same problem with log rotation, 
I thought that the problem was of centovacast control panel

**Comment by ncDevel** [comment]
@karlheyes: Your trigger solution is nice and smart, but it will also trigger the icecast internal log rotation.

**Comment by karlheyes** [comment]
not entirely sure what you are getting at there. There has always been an auto log rotation point based on the size (default 50Meg I believe currently).

**Comment by yarik2720** [comment]
it seems like kill -HUP on icecast also not works on latest release kh7

**Comment by alex-zed** [comment]
It works for me.
Unlocked in the file icecast.hml line
         <pidfile> /etc/icecast2/icecast.pid </pidfile> (the file must exist with the required permissions)

in logrotate.d/icecast

/var/log/icecast2/*.log {
	daily
	missingok
	rotate 8
    size 15M
    compress
    notifempty
    create 640 icecast2 icecast
    sharedscripts
	postrotate
    if pgrep icecast >/dev/null; then
        invoke-rc.d --quiet icecast reload > /dev/null
    fi
	endscript
}

**Comment by icastcenter** [comment]
@karlheyes Running Icecast 2.4.0-kh6 and experiencing this issue. CentovaCast losing all stats after log rotation. I will be rolling back to a previous release. Affects all CentovaCast users.

**Comment by edinsof** [comment]
@icastcenter 
this resolve centovacast problem

diff --git a/src/log/log.c b/src/log/log.c
index 3c24953..05315e1 100644
--- a/src/log/log.c
+++ b/src/log/log.c
@@ -334,7 +334,7 @@ void log_reopen(int log_id)
     _lock_logger();
     if (loglist [log_id] . filename && loglist [log_id] . logfile)
     {
-        loglist [log_id].reopen_at = (time_t)0;
+        loglist [log_id].size = loglist [log_id].trigger_level+1;
     }
     _unlock_logger();
 }

this works for me

**Comment by icastcenter** [comment]
@edinsof Do you know if this patch already in master, so if I pull from master it will be included?

**Comment by edinsof** [comment]
@icastcenter 
No.
You need find /src/log/log.c file and go to line: 337 
change
`loglist [log_id].reopen_at = (time_t)0;`

to 
`loglist [log_id].size = loglist [log_id].trigger_level+1;`

**Comment by karlheyes** [comment]
I have pushed that patch to master now

karl.

**Comment by icastcenter** [comment]
Thanks @karlheyes

**Comment by icastcenter** [comment]
Also, thanks @edinsof

**Comment by karlheyes** [comment]
just committed a possible crash on reopening bug.

karl.

**Comment by ncDevel** [comment]
Sorry for my late response to this topic. The simple solution setting the size counter to the trigger limit + 1 is working fine, but has one drawback compared the behaviour of previous versions. Now all log files are rotated. In previous versions of the server it was possible to rename a log file outside the server. Triggering a reopen then just created a new one for this file. All other files were kept and appended.

**Comment by karlheyes** [comment]
I've just committed a fix for that case today.

karl.

**Comment by ncDevel** [comment]
Thanks. Issue is solved.
