### ISSUE TITLE
Log does not reopened after HUP

### ISSUE THREAD

**Issue by 2002demon** [karlheyes/icecast-kh#192]
Hallo.
From KH7 **HUP** signal reload config file and **rename icecast.log to icecast.log.old**. (overwrite)
Previous KH versions after HUP signal does not renamed log file and just added log again to icecast.log.
If i activate logarchive i have a lot of files, becouse i use HUP very often.
Can you fix this issue?

**Comment by karlheyes** [comment]
I have made it so that if log archive is not defined then the default is to keep the file open for writing (no cycle), although it will still cycle at the limits (size or duration).  Set to 0 will cause the cycle to .old and set to 1 will cycle to log with timestamp.

Does the master build work as expected?

karl.

**Comment by topalex** [comment]
And what if I dont want log cycling at all (I prefer to use logrotate)? If I set logsize to 0 icecast renames log file when it reaches 50 MB size anyway. Is there the way to disable this?

**Comment by karlheyes** [comment]
There is always an upper limit, a filesystem dictates that.  The code current allows up to 2Gig.  50Meg was choosen to have a decent size that will still take a lot of content. Do you think you will go over 2Gig between rotates?

karl.

**Comment by 2002demon** [comment]
So, for my case, do i need to remove <logarchive>0</logarchive> ?
And if i send HUP to server, then icecast.log will be reopened?

In old KH versions at 00:00 i just move icecast.log to icecast.log.day, and then send HUP for reopening new icecast.log. How to handle correct now?

**Comment by karlheyes** [comment]
A zero value is ignored (I should probably make that threshold at least a meg) so will keep the previous setting, but the default is 50Meg, unless you override it (logsize of 2000000, is the highest consider currently, it was lower in earlier releases).    Any large value should suffice for your situation,  a simple rename and HUP will work fine for that.   Without archive set, if the limit is ever reached (eg spamming the logs or the rotation fails for long enough) then it will rename automatically to ...old and reopen a new one.

karl

**Comment by 2002demon** [comment]
I think your answer is for user topalex, becouse i know about logsize, i use 1GB in my config.
I have tested new master, so if **logarchive** is not defined in config, then this work correct for me.
HUP signal just reopen the same **icecast.log** file or create new if not exists.

But i think logarchive=0 must do the same as logarchive not set. It's still a bug, if logarchive=0.
If  logarchive=0 and we sending HUP signal, then everytime a little file icecast.log overwrite icecast.log.old **and we lost logs**. Maybe you can fix it to prevent problems by another people.

**Comment by karlheyes** [comment]
there was another log reopen case that I've fixed.  If the log was moved and then a new one created (even empty) before the HUP then the attempt was was skipped over.  I now avoid that case and avoid the archiving aspects of that case assuming the size is within limits.

karl.

**Comment by 2002demon** [comment]
Seem to be fixed.
Thank you
