### ISSUE TITLE
Logging to stderr doesn't work

### ISSUE THREAD

**Issue by spr0cketeer** [karlheyes/icecast-kh#193]
Using current git master with:

examples/icecast_minimal.xml:

```
<errorlog>-</errorlog>
<accesslog>-</accesslog>
```

logging is not going to stderr

A workaround I've found is to use named log files but with a fake logdir `<logdir>/missingdir</logdir>`  - this gets output going to stderr but sending a SIGHUP when using this kludge causes a segmentation fault in log.c - likely due to using this being a kludge, but worth checking when stderr logging is working as it should just in case it's not.

**Comment by karlheyes** [comment]
Thi should be fixed in the master now, can you confirm?

karl

**Comment by spr0cketeer** [comment]
Hi karl,

stderr logging now working and no seg fault on SIGHUP.

Thanks for fixing.
