### ISSUE TITLE
Icecast Locking up on HUP KH6+

### ISSUE THREAD

**Issue by mooseh** [karlheyes/icecast-kh#197]
Hi Karl

We have been using your KH branches for a very long time but we seem to have come across an odd issue since 2.4.0-KH6.

In order to reload our configuration we use killall -HUP icecast but since KH6 when doing this sometimes icecast falls over and doesnt return backup (unless supervisords kicks in) but we lost all of our listeners.

here's the log to show whats happening when it falls over afgter running the killall -HUP

[2017-11-30  21:21:17] INFO event/event_config_read Re-reading XML
[2017-11-30  21:21:17] INFO auth_url/alloc_thread_data ...handler data initialized
[2017-11-30  21:21:17] INFO auth_url/alloc_thread_data ...handler data initialized
[2017-11-30  21:21:17] INFO auth_url/alloc_thread_data ...handler data initialized
[2017-11-30  21:21:17] INFO auth_url/alloc_thread_data ...handler data initialized
[2017-11-30  21:21:17] INFO auth_url/alloc_thread_data ...handler data initialized
[2017-11-30  21:21:17] INFO auth_url/alloc_thread_data ...handler data initialized
[2017-11-30  21:21:17] INFO thread/ lock abort set to 0

Edit (also found this) in the syslog which im pretty sure is the reason : 
kernel: [9972993.951092] icecast[5090]: segfault at 35 ip 00007f471d010dcc sp 00007f4718f7f6e0 error 4 in libc-2.19.so[7f471cfc6000+1a1000]

King Regards
Louis Kidd

**Comment by karlheyes** [comment]
I did some logging changes in recent versions to make the writing part decoupled from the invocation. The purpose was to assist in certain areas where stalls can occur.  Unfortunately there have been a few corner cases that have flagged up problems. I think all of those are now flushed out and do not cause problems.  If you want, you can try the current master branch from github and verify it's working as intended.

karl.

**Comment by mooseh** [comment]
Hi Karl this seems to be happening on both KH6 and KH7 im taking a wild guess KH7 is the master branch?

Kind Regards

Louis Kidd

**Comment by karlheyes** [comment]
the master branch contains the post kh7 fixes, will become kh8.  You can retrieve a tarball/zip from github

karl

**Comment by mooseh** [comment]
Hi Karl

I have git cloned your master and can confirm the segdumps are no longer happening.
When do you think this will be pushed into KH8?

also rather than getting a clone link do you know where i can get the master tarball as the KH7 tarball I tried earlier today crashes still.
Kind Regards
Louis Kidd

**Comment by karlheyes** [comment]
kh8 is now released

karl.
