### ISSUE TITLE
Curl - Could not resolve host

### ISSUE THREAD

**Issue by cdgraff** [karlheyes/icecast-kh#211]
Hi @karlheyes 

I'm installing a new Icecast-kh server with latest master code, I has build them with CURL support to use auth_url, i do this before many times, but today I can't understand why got this error:

error.log:[2018-02-15  10:53:38] WARN auth_url/url_stream_start auth to server https://us-central1-demo.cloudfunctions.net/demo (/stream.aac) failed with Could not resolve host: us-central1-demo.cloudfunctions.net

I changed the real subdomain name, but if I ping and made curl I got the response correctly only fail when the call is from inside icecast process

Some idea to help me with debug? I try change the order into /etc/nsswitch.conf without lucky, any advice will be welcome!

Thanks

**Comment by karlheyes** [comment]
name resolution is not working, typically a factor with a chroot jail not configured correctly.   strace may help you identify things being looked for with name resolution

karl.

**Comment by cdgraff** [comment]
thanks! after remove chroot works perfect!
