### ISSUE TITLE
aac he v2 intro audio support

### ISSUE THREAD

**Issue by DuncanFairley** [karlheyes/icecast-kh#212]
Can AAC streams play intro audio?

I haven't managed to get it to play the stream after the introaudio file yet.

**Comment by karlheyes** [comment]
that should be fine assuming the intro is the same format as the stream, eg not in an mp4 container.  The more recent commits on master report the detected format of the intro when stream starts. In such cases then it should report AAC and the basic details.

karl.

**Comment by DuncanFairley** [comment]
Oh cool - the issue was that I was putting the introaudio in a mp4 container - I added a `-f adts` to ffmpeg and it seems to work perfectly now. Thanks!
