### ISSUE TITLE
feature request?

### ISSUE THREAD

**Issue by mooseh** [karlheyes/icecast-kh#213]
Hey there Karl 

I was wondering if you do feature requests because im looking for 1 more little piece of data from authentication methods.

to put it simply when someone hits listener_add could you possible add current connected listeners including this one that joined.

and of course vice versa for listener_left?
if not still worth a shot in the dark.

I know i can just curl the mount stats page but I just feel that would be a littler heavy especially as we have some servers with 10/100 new connections every second.

Kind Regards
MooseH

**Comment by dkwiebe** [comment]
@mooseh I believe the first item you're looking for was added here: https://github.com/karlheyes/icecast-kh/pull/181

**Comment by mooseh** [comment]
wow okay, do we know which version this was released with? 
im just going to double check what icecast is spitting out and see if its there :)

making me a very happy man guys :)
