### ISSUE TITLE
Can't set http headers

### ISSUE THREAD

**Issue by tjharman** [karlheyes/icecast-kh#221]
I'm trying to set:

```
<http-headers>
    <header name="X-Robots-Tag" value="noindex, noarchive, nofollow, nosnippet" status="200" />
    <header name="X-dns-prefetch-control" value="on" status="200" />
    <header name="Strict-Transport-Security" value="max-age=31536000" status="200" />
</http-headers>
```

Which the (original icecast) manual says is supported.

Has this been removed from the -kh branch?

Icecast 2.4.0-kh9-20180321165532
Starting icecast2
Detaching from the console
[2018-03-27  15:15:39] WARN xml/parsing warning:
[2018-03-27  15:15:39] WARN xml/parsing unknown element "http-headers" parsing "icecast" at line 2

**Comment by articobandurini** [comment]
i also encounter this issue. is there any way to set headers in icecast-kh ?

**Comment by articobandurini** [comment]
actually this WARN is missing if you upgrade to kh11 version, but the headers still not being set anyways.

**Comment by karlheyes** [comment]
2.4.0 did not have that xml tag, so those headers will not be sent, but you should certainly get the warning about it being unknown.

karl

**Comment by snahor** [comment]
@karlheyes If I add support for this, would it be merged?

**Comment by smilingpeanut** [comment]
I would also like to see support for `http-headers` added to KH. Applying HTTP headers is the only way to update stream directory metadata for the radio-browser API, which many internet radio clients rely on to power station discovery: [https://www.radio-browser.info/owners](url)

**Comment by antrys** [comment]
I just ran in the exact same problem as @smilingpeanut 
Moved to KH to stop DDoS attacks via useragent blocking, now my listing doesn't work anymore.

I would love for http-headers to be added.

**Comment by t0mtaylor** [comment]
http headers are coming.... https://github.com/karlheyes/icecast-kh/issues/373

**Comment by gunsar** [comment]
> @smilingpeanut  I would also like to see support for `http-headers` added to KH. Applying HTTP headers is the only way to update stream directory metadata for the radio-browser API, which many internet radio clients rely on to power station discovery: [https://www.radio-browser.info/owners](url)
>

I tried the latest version of Icecast 2.4.0-kh16.3, and added the headers according to the instructions on www.radio-browser.info, still not verified. maybe @karlheyes  have new plan to solve this problem in kh17 version

**Comment by tjharman** [comment]
Hey, this works in kh-17!  Thanks so much @karlheyes!!
