### ISSUE TITLE
multiple masters-servers

### ISSUE THREAD

**Issue by rcasunshare** [karlheyes/icecast-kh#236]
What is the configuration for multiple masters-servers in the XML file?

**Comment by karlheyes** [comment]
For multiple masters the syntax can be something like 
```
<master>
    <port>9000</port>
    <host>
       <ip>....</ip>
    </host>
    <host>
       <ip>....</ip>
    </host>
    ...
</master> 
```

**Comment by karlheyes** [comment]
You can also use the host tags within a relay block.

karl.
