### ISSUE TITLE
SSL Cpu Load Problem

### ISSUE THREAD

**Issue by stephanzett** [karlheyes/icecast-kh#243]
hi Community! 
I am working with icecast for several years now and don’t know what to do with my newest setup: i have to make 20-30k simul listeners happen on a sever. my testsetup is several beefy client machines (4) that suck on a large 16 core proliant sever. i had to use the kh version since the xiph version always runs only on one core (per mount). At about 15000 listeners the core was full and dropouts started to occur. so that problem i could solve with the KH version which nicely distributes the load onto all cores. Unless: as soon as i start using ssl on a mount the server starts peaking again on one core. (it also need about 3 times th cpu power with ssl). so why does icecast KH is not using all CPU cores with ssl like it does with no ssl? thx in advance.

**Comment by inetactief** [comment]
Hi, 

Do you have a solution to use SSL for all cores?
I see the same problems.

Best regards,
Michel

**Comment by jesseorr** [comment]
One method might be to use an NGINX reverse proxy in front of the Icecast server. NGINX can forward the x-forward-for header to Icecast, which KH can decode (if whitelisted), and then Icecast will run HTTP connections and Icecast can run HTTPS.

Of course a fix within the code base would be preferred, but this method might get you around your hurdle.

**Comment by inetactief** [comment]
Thanks for fast resonse and the suggestion.
 Unfortunately i ihave too little knowledge about NGINX reverse proxy.

**Comment by karlheyes** [comment]
been busy with other things so missed this.  You didn't say but you have `<workers>` in limits set to the number of working threads,  eg set to 16.

karl.

**Comment by inetactief** [comment]
Thank you Karl i will try that when reboot the server.

**Comment by karlheyes** [comment]
you can change that on-the-fly.  just edit your xml and trigger a reload, HUP signal or via the admin page.   The threads are created without dropping existing clients and are shuffled around periodically.

karl.

**Comment by inetactief** [comment]
We use 2 cores and i set in the config:
 in <limits> 
<workers>2</workers>
....
I try pkill -HUP icecast 
but in top i see stil one proc /core.

**Comment by karlheyes** [comment]
you should see multiple threads for icecast, how many and look at how much each is using.

karl.

**Comment by inetactief** [comment]
Hi Karl,
I check in top i see one icecast 
When is check ps -aux | grep ice i see only one proc.

Michel

**Comment by karlheyes** [comment]
if you look at top, press the H,  with ps, there are 2 variants depending on the bsd/sysv semantics

eg  ps auxH   or ps -eLf

karl.

**Comment by karlheyes** [comment]
will assume this is resolved now.  FYI  kh14 is up and has all latest fixes.
 
karl
