### ISSUE TITLE
Last build crashing

### ISSUE THREAD

**Issue by edinsof** [karlheyes/icecast-kh#247]
HI
i updated yesterday our icecast kh version but it's crashing and make core files. on centos 7

**Comment by karlheyes** [comment]
I just updated master with a crash fix.  I cannot tell if that resolves what you experienced.  If the core shows a crash within the introfile routine then it does.

karl

**Comment by edinsof** [comment]
The crash error was solved it same showed:
Mar 15 15:58:02 server2 kernel: icecast[16791]: segfault at 20 ip 0000000000429405 sp 00007f98982abbe0 error 4 in icecast (deleted)[400000+53000]

thank you
