### ISSUE TITLE
kh12 win32/win64 not found

### ISSUE THREAD

**Issue by KruegerDead** [karlheyes/icecast-kh#250]
Latest icecast kh 12 not uploaded to sourceforge. When try download: 
`The "/icecast-2.4.0-kh12_..kh12_win64_setup.exe" file could not be found or is not available. Please select another file.`

https://sourceforge.net/projects/icecastkh/files/

**Comment by karlheyes** [comment]
ok, that should be fixed.

karl.

**Comment by KruegerDead** [comment]
Thanks Karl! Now all ok.
