### ISSUE TITLE
Update CORS to allow clients to send Icy-MetaData header

### ISSUE THREAD

**Issue by trilliot** [karlheyes/icecast-kh#258]
Some providers (e.g.: GoodBarber) provide HTML5 audio players that read metadata directly from the audio stream.
However, the `Icy-MetaData` request header is not currently allowed by the CORS policy (it is missing in the `Access-Control-Allow-Headers`).

It would be great to allow them to send the `Icy-MetaData` request header so that they can receive the `icy-metaint` response header to parse metadata accordingly.

See #257

**Comment by karlheyes** [comment]
merge done

karl.
