### ISSUE TITLE
How to (cross-) compile for Windows ?

### ISSUE THREAD

**Issue by EarvinKayonga** [karlheyes/icecast-kh#259]
Hi @karlheyes,

I'm pretty new to icecast (and m4-based projects in general). Could u please provide the steps to successfully build icecast for windows ?

Thx

**Comment by karlheyes** [comment]
kind of a black art really. I use mingw on my setup to create the binaries but I need to shp the libs in the installer to allow to run so those binaries sit in a pre-made install area.  The actual build though is not too bad, I use the mingw64-configure and make

karl

**Comment by EarvinKayonga** [comment]
Thx @karlheyes, 
We continued with Linux after all. :)
