### ISSUE TITLE
Icecast KH 12 memory leak

### ISSUE THREAD

**Issue by hmorneau** [karlheyes/icecast-kh#261]
Seems like it's leaking memory, I have a process that is now using 3gb of ram and it keep increasing until I restart it.

**Comment by karlheyes** [comment]
there was a leak case with auth, that is now fixed.

karl.

**Comment by hmorneau** [comment]
Humm, ok, I'm not using auth. I will update it and report back.

**Comment by karlheyes** [comment]
will close this now that kh14 is out.  Any further issues then raise a report with details.

karl.
