### ISSUE TITLE
introaudio bitrate matching 

### ISSUE THREAD

**Issue by DuncanFairley** [karlheyes/icecast-kh#262]
When playing introaudio before an MP3 stream, the bitrate should match. Does this apply to sample rate as well? stereo vs mono?

**Comment by kevev** [comment]
I only have trouble when sample rate does not match. Using different bitrates does not give me any issues.

**Comment by karlheyes** [comment]
generally speaking, mp3 streams with variable bitrates often work but some players have been known to have problems with them.  Samplerate and channel changes are the next level of confusion for players, as some more of these will have problems (may be tried to the audio system they are using, eg direct  hardware).

karl.
