### ISSUE TITLE
listener_add callback property 'listeners' empty

### ISSUE THREAD

**Issue by franzwarning** [karlheyes/icecast-kh#266]
Hi There,

I've noticed that the `listeners` property in the `listener_add` auth url callback is empty whenever the `<mount-name>` has any sort of regex (or *) in it. For example, this mount name reports the correct listeners:
```
<mount-name>/test.ogg</mount-name>
# output: 'listeners': ['0']
```
whereas this one reports the empty listeners:
```
<mount-name>/*.ogg</mount-name>
# output: 'listeners': ['']
```

I believe the issue stems [here](https://github.com/karlheyes/icecast-kh/blob/c6e5d835fedba1e0ed219e40adf87659036d6187/src/auth_url.c#L499)

Perhaps instead of `auth->mount` we can just use `mount`?

Thanks for the awesome repo. Would love to hear your thoughts!

**Comment by karlheyes** [comment]
This is now fixed. actually the 'mount' you referred to is the encoded requested mount which can include parameters so may also not find a match in stats. The actual setting was in auth_user.

karl.

**Comment by franzwarning** [comment]
Thx @karlheyes
