### ISSUE TITLE
Location on listener_add auth

### ISSUE THREAD

**Issue by 2002demon** [karlheyes/icecast-kh#270]
Hello Karl!
I try to redirect listeners to another server over listener_add auth. If i set **header('Location: http://newurl.com/mount');** in auth.php, then icecast wait 5 sec and redirect user. The reason here is that CURL in your code auth_url.c use this option:
curl_easy_setopt (atd->curl, CURLOPT_FOLLOWLOCATION, 1);
This mean that curl make intern redirection and download content from a radio stream.
Maybe you can remove this option, or add new feature header for redirects?
Example:
icecast-auth-location: http://newurl.com/mount

**Comment by evgenmedia** [comment]
So... have the same problem) 

Any solutions with out own fork is available? 

In my case Icecast-KH follows the redirect and after than ban auth server as "slow"
