### ISSUE TITLE
segfault Icecast 2.4.0-kh12-20191030235808

### ISSUE THREAD

**Issue by AxisNL** [karlheyes/icecast-kh#271]
Hi,

Icecast_kh is crashing for us once in a while. This is the first one after we upgraded to kh12. I see the following entry in my /var/log/messages on CentOS7:

Nov 25 15:43:08 server-26 kernel: [490050.878749] icecast[3915]: segfault at 7f265c04f878 ip 00007f27686357f9 sp 00007f27648f69f0 error 4 in libc-2.17.so[7f27685b5000+1c3000]

This version is supplied by our control panel provider, and I have no idea how I can reproduce the segfault, or how I can generate a coredump.

This icecast instance in question has three mountpoints. Two incoming audio streams and an autodj. All mp3.

Perhals the info above points you in any direction of where to search for the problem?

Kind regards,
Angelo Hongens

**Comment by karlheyes** [comment]
It's probably the corruption case that I've fixed in kh13.  Hard to tell precisely as corruption cases can show in different ways but it's more than likely to be that.

karl.

**Comment by AxisNL** [comment]
Great, haven't seen it in kh13 yet!
