### ISSUE TITLE
stream_auth is called every 10 seconds

### ISSUE THREAD

**Issue by radioboss** [karlheyes/icecast-kh#273]
I use URL authentication for sources like this (configured in <mount> section)
`        <authentication type="url">
            <option name="stream_auth" value="http://.../icecast_auth.php"/>
            <option name="auth_header" value="icecast-auth-src: 1"/>
        </authentication>`

And I see that the auth script is being called every 10 seconds (when the source is already connected and streaming) - why is that?

**Comment by DuncanFairley** [comment]
I've seen this happen when I had an extra copy of the streaming client trying to connect. Check your icecast logs to see which IP is responsible.

**Comment by radioboss** [comment]
Turned out it was stats requests that also triggered strteam_auth.
