### ISSUE TITLE
Install Kh-12 Debian 9 problem

### ISSUE THREAD

**Issue by rcasunshare** [karlheyes/icecast-kh#274]
Hi, how is the Kh-12 version installed on Debian 9 Strectch? Because it doesn't let you install.

The following packages have unmet dependencies:
 icecast2 : PreDepends: init-system-helpers (>= 1.54~) but 1.48 is to be installed
            Depends: libc6 (>= 2.27) but 2.24-11+deb9u4 is to be installed
E: Unable to correct problems, you have held broken packages.

the libc6 library in debian 9 only version 2.24 is allowed

I will appreciate the help

**Comment by marillat** [comment]
This package come from where ?

**Comment by rcasunshare** [comment]
> This package come from where ?

https://www.deb-multimedia.org/pool/main/i/icecast2-dmo/icecast2-dmo
icecast2_2.4.0kh12-dmo1_amd64.deb

**Comment by marillat** [comment]
The best was to send an e-mail to the repository maintainer (me).

You're not using the right package

2.4.0kh12-dmo1 is the package for stable/buster

2.4.0kh6-dmo1+deb9u1 is the package for oldstable/stretch

```
$ dak ls icecast2
icecast2   | 1:2.3.3kh11-dmo1        | oldoldstable
icecast2   | 1:2.4.0kh6-dmo1+deb9u1  | oldstable
icecast2   | 1:2.4.0kh12-dmo1~bpo9+1 | oldstable-backports
icecast2   | 1:2.4.0kh12-dmo1        | stable
icecast2   | 1:2.4.0kh12-dmo1        | testing
icecast2   | 1:2.4.0kh12-dmo1        | unstable

```

**Comment by rcasunshare** [comment]
> The best was to send an e-mail to the repository maintainer (me).
> 
> You're not using the right package
> 
> 2.4.0kh12-dmo1 is the package for stable/buster
> 
> 2.4.0kh6-dmo1+deb9u1 is the package for oldstable/stretch
> 
> ```
> $ dak ls icecast2
> icecast2   | 1:2.3.3kh11-dmo1        | oldoldstable
> icecast2   | 1:2.4.0kh6-dmo1+deb9u1  | oldstable
> icecast2   | 1:2.4.0kh12-dmo1~bpo9+1 | oldstable-backports
> icecast2   | 1:2.4.0kh12-dmo1        | stable
> icecast2   | 1:2.4.0kh12-dmo1        | testing
> icecast2   | 1:2.4.0kh12-dmo1        | unstable
> ```

version 2.4.0kh6-dmo1+deb9u1 hangs up and stops working after 24 hours

**Comment by marillat** [comment]
What are  your calling stop working ?

**Comment by rcasunshare** [comment]
Stop working after 24 hours running. And I have to start again manually.

**Comment by marillat** [comment]
> Stop working after 24 hours running. And I have to start again manually.

Nothing in the icecast log ?

**Comment by rcasunshare** [comment]
Previously I used the kh-11 version and I never had problems.

**Comment by karlheyes** [comment]
kh13 is out now. It does fix a corruption issue that can appear in kh12

karl.

**Comment by rcasunshare** [comment]
> > Stop working after 24 hours running. And I have to start again manually.
> 
> Nothing in the icecast log ?

Hello, please urgently update deb-multimedia, the Icecast-KH for Debian Stretch 9 to version KH13 that corrects serious problems.

**Comment by karlheyes** [comment]
kh14 is out now.

karl
