### ISSUE TITLE
fallback override bug - KH13

### ISSUE THREAD

**Issue by mooseh** [karlheyes/icecast-kh#279]
Hey Karl

KH13 seems to have developed a bug when using fallback-override
when the stream returns back to the primary mount it drops all listeners
we tested right from KH9 upwards without issues until reaching KH13
we also then checked your master branch and saw the following commit which has resolved our issues https://github.com/karlheyes/icecast-kh/commit/08cd9a7f9f48bff6f214c763757c8cfa6abbc144

when do you think you could push this into a release as we are in desperate need for the release link as we use ansible to automatically install your versions.

we also cannot return to kh12 due to corruption bug
and we cannot return back to before then due to segfaults on killhup.

**Comment by karlheyes** [comment]
kh14 now out
