### ISSUE TITLE
Slow response of default icecast web admin panel

### ISSUE THREAD

**Issue by eranwo** [karlheyes/icecast-kh#284]
I need to upgrade my icecast from Icecast 2.4.0-kh1 to the latest ver. 
As i can see, there are problems of very slow response of the all web pages that came "out-of-the box" within the default installsion (index, status.xsl ...). I've tested on the same server that is currently running 2.4.0-kh1..
Is it just me?

**Comment by karlheyes** [comment]
hmm, small documents like the html files should be fairly quick coming through. xsl files can be slow if you have a lot of data in them but I don't know what you are experiencing.  a single stream should not have much data at all for status.xsl.  

karl

**Comment by eranwo** [comment]
@karlheyes I meant everything became slow only in **ssl** mode
includes the stream time to load

**Comment by karlheyes** [comment]
again nothing really to go on. you could strace the process to let me know what you are seeing?  I presume you are talking of low load as you don't say anything of sources or listener counts.  you mention nothing of the hardware you are running on or the load it has or the number of workers you have configured in the xml

karl.

**Comment by karlheyes** [comment]
If kh14 is still showing this then reopen and give me details.

karl.
