### ISSUE TITLE
IP Bans from <deny-ip> list applying to the proxy's IP, not the "X-Forwarded-For" IP if supplied

### ISSUE THREAD

**Issue by SlvrEagle23** [karlheyes/icecast-kh#286]
Hello!

We're taking advantage of the `X-Forwarded-For` support in order to put a reverse proxy in front of the broadcasted station. In our logs and in the listener statistics of Icecast, it shows the correct forwarded IP, but when calculating whether an IP is banned and should be rejected, it's using the proxy's IP instead, suggesting the banned determination happens before that IP switchover happens.

**Comment by karlheyes** [comment]
latest commit to master should deal with this now.   The XFF is now done earlier and then checked for acceptance. Usual rules for bans apply.

karl
