### ISSUE TITLE
Segfaults still on latest commit (2c37d44)

### ISSUE THREAD

**Issue by djamps** [karlheyes/icecast-kh#287]
After about 6 hrs:

Mar  6 02:52:37 c352vm3 icecast: *** Error in `/usr/local/bin/icecast': malloc(): memory corruption (fast): 0x00007f59e8000940 ***
Mar  6 02:52:37 c352vm3 systemd: icecast.service: main process exited, code=killed, status=6/ABRT

Downgraded to KH10 (last segfault free version for us still at this point).

**Comment by karlheyes** [comment]
there's a number of changes since kh10,  so let me know how I can help. 

karl

**Comment by karlheyes** [comment]
I've just fixed an issue that can lead to an abort case, which would not of been in kh10. However it is next to impossible to know whether what you have experienced is down to this. it was present if stream auth was used.

karl

**Comment by karlheyes** [comment]
kh18 is up now.  You should let me know how that works out with whatever setup you have.
