### ISSUE TITLE
Sending CORS header in icecast-kh 2.4

### ISSUE THREAD

**Issue by dansteingart** [karlheyes/icecast-kh#297]
(quick thanks for excellent work KH!)

I am new to the kh branch and I cannot enable CORS out of the box. In the standard icecast XML it is enabled by the lines

```
    <http-headers>
        <header name="Access-Control-Allow-Origin" value="*" />
    </http-headers>

```
But as I found out reading through the issues the icecast-kh branch does not support these headers.

Subsequently, when I try to access the streams through a web browser (I am making an application where the html files are served elsewhere from the stream), chrome throws these errors:

```
Access to audio at 'https://icecast-kh.host/mount' 
from origin 'https://html.host' has been blocked by CORS policy: 
No 'Access-Control-Allow-Origin' header is present on the requested resource.

```

Given that it is clear CORS works in this branch, how do I enable it? Thank you.

**Comment by karlheyes** [comment]
That header should be present without any xml needed but you have not said the version and browsers can be messy regarding the request they make.  check the response you currently get with

curl -v -o /dev/null http://icecast-kh.host/mount

ctrl-C to stop. The headers should be displayed. Let me also know what the access log reports for your chrome attempt.

karl

**Comment by dansteingart** [comment]
thanks so much, just figured it out: I wasn't serving the `.xslt` files correctly.
