### ISSUE TITLE
CORS and withCredentials flag

### ISSUE THREAD

**Issue by waster** [karlheyes/icecast-kh#300]
Hello,

For CORS requests Icecast always returns `Access-Control-Allow-Origin: *` header. Bit it does not work with XHR requests from browsers that have `withCredentials` flag (for cookie support for example). Server must return two headers when this flag was set:
```
Access-Control-Allow-Origin: ORIGIN
Access-Control-Allow-Credentials: true
```
Is it possible to add support for such requests, may be some configuration directive?

**Comment by karlheyes** [comment]
Can you check the kh15 release to verify that is working as expected.

karl

**Comment by waster** [comment]
Thanks! Seems to be working now.
