### ISSUE TITLE
server_name update while connected to Icecast

### ISSUE THREAD

**Issue by hmorneau** [karlheyes/icecast-kh#305]
Hi,

It seems like it's impossible to update the server_name while connected to it.
"If you want to change the title of the stream etc, which Darkice can send, 
then no you can't do this.  It's set when you connect and won't change 
unless you disconnect and reconnect."

Ref: http://lists.xiph.org/pipermail/icecast/2010-December/011774.html

Do you think you could push an update on this? I understand that currently connected listeners won't see the update and that's fine.

Thanks.

**Comment by karlheyes** [comment]
The http headers are sent at the beginning of the connection so you don't really get another chance in the same connection.  There would need to be another route to update that info which would likely be under /admin/ to pass those updated details through to the internal storage for that.  It's never been a sought after thing and may confuse certain aspects like adding a length, or icy-metaint field so would proably need limiting to certain entries.

karl.

**Comment by hmorneau** [comment]
ok, thanks for the update.
