### ISSUE TITLE
Two ssl certificates for two domains in icecast

### ISSUE THREAD

**Issue by Swiftgti** [karlheyes/icecast-kh#306]
I don’t find the way to have Multiple certificates , so icecast can send correct ssl certificates for different domains
Like domain1.com and domain2.com
Why it’s useful this ? So one icecast server could be also used as a backup server of another server
so if fails one server you change a record of the domain and you send traffic from one server to another, but they have different domains. ! And you need certificates of both domain of each server installed in icecast. 

Thanks.

**Comment by karlheyes** [comment]
While you can have a single cert with multiple domains listed, icecast itself does not handle multiple certs, one for each domain. It does not yet handle virtual hosting as such.  It's one of those TODO type of things.

karl.

**Comment by Swiftgti** [comment]
Thank you Karl. I solve it as you said.
