### ISSUE TITLE
GCC10 build issue

### ISSUE THREAD

**Issue by zygmund2000** [karlheyes/icecast-kh#307]
Hi,

I have Arch Linux with new GCC 10 and I have some errors during compilation:

`CCLD     icecast
/usr/bin/ld: client.o:(.bss+0x24): multiple definition of `worker_count'; slave.o:(.bss+0x60): first defined here
collect2: error: ld returned 1 exit status
make[3]: *** [Makefile:564: icecast] Error 1`

I know the new gcc 10 brings some changes because it's not my first problem with it but now I don't know how to solve it myself.

**Comment by karlheyes** [comment]
I don't have gcc 10 installed yet, but the error should now be resolved in master.

karl

**Comment by zygmund2000** [comment]
Yes, it solved this issue.

thx
