### ISSUE TITLE
On-connect and on-disconnect without mountpoint argument bug. (kh14)

### ISSUE THREAD

**Issue by DroidU** [karlheyes/icecast-kh#316]
I have a script that runs when on-connect and on-disconnect. However, since kh14, the script has not received the mountpoint argument. This works well with kh13 and older versions.

**Comment by karlheyes** [comment]
I have checked and commited a fix for this.  Can you verify the master tree for this?

karl.

**Comment by DroidU** [comment]
I checked it. It works well.
