### ISSUE TITLE
Change Default metaInt

### ISSUE THREAD

**Issue by hmorneau** [karlheyes/icecast-kh#321]
Hi,

How can we change the metaInt value without having to specify it on each mount point?

**Comment by karlheyes** [comment]
only in source, in formap_mp3.c, ICY_METADATA_INTERVAL.   You can of course use the wildcard mount to do a range of mountpoints but that may not be suitable.

karl.

**Comment by hmorneau** [comment]
Thanks. we managed to do with with wildcard.
