### ISSUE TITLE
SSL renewal

### ISSUE THREAD

**Issue by hmorneau** [karlheyes/icecast-kh#322]
I have seen somewhere that KH support cert renewal without having to restart Icecast. 

I have tried this just now, I have updated the pem file with a new cert and when I visit the stream URL in https, it still shows the old cert. Any idea if a restart is needed? 

I already confirmed that the pem file have the new cert.

**Comment by karlheyes** [comment]
trigger a reload either with HUP signal or via the admin page

karl

**Comment by hmorneau** [comment]
HUP signal is working :) 

Does Icecast reload everything from the conf file with it?

**Comment by karlheyes** [comment]
most things are, certain things relating to security concerns are not.  eg adding listening ports is fine but usually adding ports less than 1024 is not possible, changing the chroot or changeowner aspects are also problematic over a reload.  Those don't tend to be the things people change though.

karl.
