### ISSUE TITLE
access.log not rotating when used with Centovacast

### ISSUE THREAD

**Issue by BenHippynet** [karlheyes/icecast-kh#326]
I'm using Icecast 2.4.0-kh15 on a Centovcast server. I'm having a problem when Centovacast rotates the logs.

A new access.log file will be created and the old log rotated to access.log.1 but Icecast-kh will append to access.log.1 and the new access.log stays at 0 bytes.

Has anybody else seen this behaviour?

**Comment by BenHippynet** [comment]
Looking through past issues #313 pretty much describes the issue but was apparently fixed in kh15. Has something changed to re-introduce it?

**Comment by karlheyes** [comment]
Can you try with the master tree, it is essentially kh15 with one change.  Just want to see if that is the issue.  If the issue still persists then let me know.

karl

**Comment by BenHippynet** [comment]
Hi Karl,

I've installed from the master tree on two of my servers. I'll give it some time to see if the logs rotate and let you know.

Ben

**Comment by BenHippynet** [comment]
That seems to have done the trick, thanks Karl.
