### ISSUE TITLE
Feature Request: Add Log Paths if they do not exist

### ISSUE THREAD

**Issue by mooseh** [karlheyes/icecast-kh#327]
We had an issue where we created some mounts with some custom log paths, and unfortunately we were getting random segmentation faults because the log paths did not exist. when icecast reloads can it create those log paths? this would be a very helpful feature.

**Comment by karlheyes** [comment]
hmm, the directory components are not created currently, generally not been a factor.  I suppose with macro expansion, the ability to have more specific paths could be useful and directory creation could be apart of that. 

karl.

**Comment by mooseh** [comment]
thanks karl this would be extremely helpful!
