### ISSUE TITLE
https source for relay

### ISSUE THREAD

**Issue by waster** [karlheyes/icecast-kh#342]
Hello, 

I'm trying to relay https source, but getting connection error about this. For example, this relay does not work for `https://username:password@IP:10000/mount`:

```
<relay>
        <server>IP</server>
        <port>10000</port>
        <mount>/mount</mount>
	<username>username</username>
	<password>password</password>
        <local-mount>/mount</local-mount>
</relay>
```

Is https relaying supported by icecast-kh?

**Comment by rustyhodge** [comment]
What is the source server running? What is the error you get? 
I am guessing that when you think you're relaying from a -kh SSL-enabled server, because it uses or doesn't use SSL depending on the connection request, that even if connecting to a port 443 on a SSL-enabled -kh server it will make the connection in the clear.

**Comment by karlheyes** [comment]
actually this is now in the master tree.  The setup part was re-coded and now can use the SSL/TLS routines. It has allowed me to flush a couple of things out.  but now you can enable with a ssl or tls boolean tag on the host eg
```
<relay>
    <local-mount>/stream</local-mount>
    <port>8000</port>
    <host tls="true" server="master1" mount="/live" />
    <host tls="true" server="master2" mount="/backup" />
 </relay>
```

I suspect a default should still be non-encrypted but a redirect can still trigger it with https://

karl

**Comment by tjharman** [comment]
Hi Karl,

I'm unable to get this to work - am I doing something wrong?

Currently using the very latest from github - 
{12:58}~/icecast-kh:master ✗ ➭ git status
On branch master
Your branch is up to date with 'origin/master'.

`    <relay>
        <local-mount>/x</local-mount>
        <host ssl="true" server="digitalstreams.mediaworks.nz" port="443" mount="/chx_net_high_icy" />
        <on-demand>0</on-demand>
        <relay-shoutcast-metadata>1</relay-shoutcast-metadata>
    </relay>`

I've tried ssl=true and tls=true but I can't get my icecast-kh to restream this ssl stream.

Thanks!
