### ISSUE TITLE
Is it possible to set streamURL for a mount point in config file?

### ISSUE THREAD

**Issue by john-a-harris** [karlheyes/icecast-kh#345]
Is it possible to set the StreamUrl for a stream in the 'mount' section of the server configuration? I can set via a metadata update call (although not via the admin UI, it seems), but since I'm only wanting a static url (for a channel logo), I'd rather set it once in the config if possible. Can anyone help?

**Comment by hotenov** [comment]
If you really mean `stream-url` which is displayed on Admin UI as **server_url** - YES, you can.
Set it in mount section of `icecast.xml` for your mount, for example:
```xml
<mount type="normal">
    <mount-name>/example-complex.ogg</mount-name>
    <stream-url>http://some.place.com</stream-url>
</mount>
```

You can override _(or specify)_ another mount attributes _(settings)_, see in [documentation](https://icecast.org/docs/icecast-trunk/config_file/#mount-specific-settings).

**Comment by john-a-harris** [comment]
Thanks for the response, but no, I do mean 'StreamURL'. See an example output from ffprobe:

> Input #0, aac, from 'https://stream.radioparadise.com/aac-128':
>   Metadata:
>     icy-br          : 128
>     icy-description : DJ-mixed blend of modern and classic rock, electronica, world music, and more. Always 100% commercial-free
>     icy-genre       : Eclectic
>     icy-name        : Radio Paradise (128k aac)
>     icy-pub         : 1
>     icy-url         : https://radioparadise.com
>     StreamTitle     : Sonny Chillingworth - Moe 'Uhane (Dream Slack Key)
>     StreamUrl       : http://img.radioparadise.com/covers/l/B0000030MF.jpg
>   Duration: N/A, bitrate: 128 kb/s
>     Stream #0:0: Audio: aac (LC), 44100 Hz, stereo, fltp, 128 kb/s

The icy-url equates (I think) to 'stream-url'. 'StreamUrl' is part of the metadata, as far as I understand it.

**Comment by hotenov** [comment]
With example, it's more clear :)

Unfortunately, image for stream is available only in Shoutcast configuration file. Not for Icecast for now.

**Comment by gunsar** [comment]
this is so cool, i tried your stream
open do browser and in foobar enter the url https://stream.radioparadise.com
sound work (in foobar) immediately appears player and sound work (in browser)
did it change in icecast.xml? how to custom?
Please help

> Thanks for the response, but no, I do mean 'StreamURL'. See an example output from ffprobe:
> 
> > Input #0, aac, from 'https://stream.radioparadise.com/aac-128':
> > Metadata:
> > icy-br          : 128
> > icy-description : DJ-mixed blend of modern and classic rock, electronica, world music, and more. Always 100% commercial-free
> > icy-genre       : Eclectic
> > icy-name        : Radio Paradise (128k aac)

**Comment by karlheyes** [comment]
tags like that (ie inline metadata) if possible are settable via the admin metadata hook , eg url=...
