### ISSUE TITLE
listener_add Accept-Language

### ISSUE THREAD

**Issue by mickaelmonsieur** [karlheyes/icecast-kh#353]
Hello,
In the listener_add is it possible to add in the POST fields the header "Accept-Language" ?  (like useragent)
Thanks

**Comment by karlheyes** [comment]
The headers supplied by the client, if available, will be getting passed through in POST with default prefix of ClientHeader-
if the headers option has that set in the list.  It was something merged from the xiph tree so I have to document it

so in the above case it should appear as ClientHeader-Accept-Language.
