### ISSUE TITLE
No mountponts display in admin - 	Icecast 2.4.0-kh15

### ISSUE THREAD

**Issue by t0mtaylor** [karlheyes/icecast-kh#361]
No mountponts display in admin - 	Icecast 2.4.0-kh15

Mountpoint configured, doesnt display?

**Comment by boteman** [comment]
If there is no stream, then the mount point will not appear in the list. This is normal behavior.

**Comment by t0mtaylor** [comment]
Just tested and your right 👍  would be there if theres a way to see the, without any connection- i find if you provide a fallback stream they will appear with no connection
