### ISSUE TITLE
Custom auth realm

### ISSUE THREAD

**Issue by art1c0** [karlheyes/icecast-kh#362]
I'd like to pass custom message in the Auth window using standard "realm" feature.
Now it looks like this "Please enter a valid login name and a password for realm icecast.", see screenshot from VLC player:

<img width="468" alt="Screen Shot 2022-03-14 at 10 44 46" src="https://user-images.githubusercontent.com/1811630/158136577-51030dbc-9152-43d9-bac2-990816d8e782.png">

I tried to set the headers like this:
('icecast-auth-user', '0')
('icecast-auth-message', '401 ' + message)
but no luck.

Please suggest how this can be achieved.

**Comment by karlheyes** [comment]
realm is an available authentication option.  I suppose it could be something sent by the auth server but that is not coded in.
