### ISSUE TITLE
Setting Icecast-KH SSL on Ubuntu doesn't work

### ISSUE THREAD

**Issue by gunsar** [karlheyes/icecast-kh#363]
please guide with complete SSL Icecast-KH on ubuntu
- I tried SSL Icecast 2.4.4 on ubuntu it work
- I tried Icecast-KH SSL on windows it work
- I tried Icecast-KH SSL on ubuntu it doesn't work
try all of the above with the same settings in icecast.xml, only SSL Icecast-KH on ubuntu doesn't work, everything else is normal
Please help

**Comment by cdgraff** [comment]
Share your error and compilation params, I'm using into Ubuntu with SSL.

**Comment by gunsar** [comment]
not an error
but opening with http:// runs normally
whereas using https:// does not open and does not work

add on icecast.xml

```
<listen-socket>
    <port>443</port>
    <ssl>1</ssl>
</listen-socket>
<ssl-certificate>/xxxx/xxxx/bundle.pem</ssl-certificate>
```

on windows icecast-kh works fine, on ubuntu icecast 2.4.4 (non KH) also works fine.
that's why i'm confused


> Share your error and compilation params, I'm using into Ubuntu with SSL.

**Comment by cdgraff** [comment]
`./configure --with-curl-config=/usr/bin/curl-config --with-openssl && make -j8  && make install`

Secret here is:  --with-openssl 

later both lines are needed:
```
        <ssl-private-key>privkey.pem</ssl-private-key>
        <ssl_certificate>fullchain.pem</ssl_certificate>
```


let me know if works for you.

**Comment by gunsar** [comment]
still not working, https:// not working, http:// working fine
do you have a complete tutorial to install step by step icecast-kh plus SSL on ubuntu? I'm afraid there are errors and install differences
Thank you in advance

> `./configure --with-curl-config=/usr/bin/curl-config --with-openssl && make -j8 && make install`
> 
> Secret here is: --with-openssl
> 
> later both lines are needed:
> 
> ```
>         <ssl-private-key>privkey.pem</ssl-private-key>
>         <ssl_certificate>fullchain.pem</ssl_certificate>
> ```
> 
> let me know if works for you.

**Comment by cdgraff** [comment]
Please clean de logs and start again, if something is wrong into the SSL process you will se some lines of logs mention the issue.
BTW, you have 443 Firewall open?

please upload and share your logs to help

**Comment by gunsar** [comment]
I'm confused all the ways have been done, but the result is the same. If you wish, may I ask for the full tutorial, it's up to you whether you want it in written form or video. thanks in advance, regards...

> Please clean de logs and start again, if something is wrong into the SSL process you will se some lines of logs mention the issue. BTW, you have 443 Firewall open?
> 
> please upload and share your logs to help
