### ISSUE TITLE
fallback dont work after update to 2.4.0-kh16

### ISSUE THREAD

**Issue by edinsof** [karlheyes/icecast-kh#371]
fallback dont works on centovacast installation.

Before update when access to /live if offline it redirects to /autodj

`<mount cc="main">
    <mount-name>/stream</mount-name>
    <fallback-mount>/live</fallback-mount>
    <fallback-override>1</fallback-override>
    <fallback-when-full>0</fallback-when-full>
    <public>-1</public>
  </mount>
  <mount>
    <mount-name>/live</mount-name>
    <intro></intro>
    <fallback-mount>/autodj</fallback-mount>
    <fallback-override>1</fallback-override>
    <fallback-when-full>0</fallback-when-full>
    <public>-1</public>
  </mount>
  <mount cc="autodj">
    <mount-name>/autodj</mount-name>
    <intro></intro>
    <fallback-mount></fallback-mount>
    <fallback-override>1</fallback-override>
    <fallback-when-full>0</fallback-when-full>
    <charset>UTF-8</charset>
    <public>-1</public>
    </mount>`

**Comment by gunsar** [comment]
same problem, even after server relay stop, the audio gets stacked and stops

**Comment by karlheyes** [comment]
I've cut an interim release kh16.1 which should resolve that, can you verify?

**Comment by karlheyes** [comment]
ok, I've put a win64 build on my site, link is 

https://karlheyes.github.io/icecast-2.4.0-kh16.1_win64_setup.exe

**Comment by gunsar** [comment]
> ok, I've put a win64 build on my site, link is
> 
> https://karlheyes.github.io/icecast-2.4.0-kh16.1_win64_setup.exe

@karlheyes 
earlier out of curiosity, I suddenly reinstalled the VPS to the ubuntu version hahaha, and the results of the icecast-2.4.0-kh16.1 linux update file run normally both relay and follback. thank's
now i will try windows version.
