### ISSUE TITLE
KH16.2 hang on reload SIGHUP

### ISSUE THREAD

**Issue by patphobos** [karlheyes/icecast-kh#375]
Hi Karl,

Sorry, another issue with KH16.2.
icecast process is hanging after a SIGHUP. Even, whitout any modification on the configuration.

reload command used : kill -HUP <pid>

[error.log](https://github.com/karlheyes/icecast-kh/files/10259850/error.log)
[access.log](https://github.com/karlheyes/icecast-kh/files/10259851/access.log)
[icecast.xml.txt](https://github.com/karlheyes/icecast-kh/files/10259853/icecast.xml.txt)
[valgrind.log](https://github.com/karlheyes/icecast-kh/files/10259857/valgrind.log)

**Comment by karlheyes** [comment]
missed a release call on previous commit from an exit out of the override setup. The master tree should be fine now

**Comment by patphobos** [comment]
not hanging anymore on reload. Thanks. i'll now give it a try with my full configuration.
