### ISSUE TITLE
Listener statistic data with cloudflare proxy is not detected real IP

### ISSUE THREAD

**Issue by gunsar** [karlheyes/icecast-kh#377]
@karlheyes 

i did experiment on linux and windows icecast-kh16 and linux icecast-kh17 then enable proxy from cloudflare
in icecast.xml i added ssl data

`<ssl-certificate>/etc/icecast-kh/bundle.pem</ssl-certificate>`

then i listen using foobar with cloudflare ssl address running normally, but check in /admin.html

List Clients
IP : 162.158.170.xx
Connected (seconds) : 263
Lag (bytes) : 0
User Agent : foobar2000/1.6.14
Action : Kick

IP : 162.158.170.xx (this is cloudflare IP) not the internet IP that I use. The IP that I use is 182.xx.xx.xx

how do you set it so that the statistics detect the original IP, while still enabling the proxy on cloudflare.

thank's

**Comment by rrolla** [comment]
@gunsar this should work add to your icecast config your cloudflare ip `162.158.170.xx`
```xml
<!-- If behind reverse proxy, set here its ip
<x-forwarded-for>162.158.170.xx</x-forwarded-for>
```
This option is from version 2.3.3-kh1 https://github.com/karlheyes/icecast-kh/blob/master/NEWS#L412

**Comment by gunsar** [comment]
@rrolla 
Thank you for your advice.
If only 1 cloudflare IP is received (fixed cloudflare IP) it might work fine. The problem is that each listener is confirmed to get a different Cloudflare IP.
But I tried to use azuracast and enable Cloudflare proxy, listener IP detected in statistics is their real IP, not Cloudflare IP.

> <!-- If behind reverse proxy, set here its ip
> <x-forwarded-for>162.158.170.xx</x-forwarded-for>
> ```
> 
> This option is from version 2.3.3-kh1 https://github.com/karlheyes/icecast-kh/blob/master/NEWS#L412

**Comment by rrolla** [comment]
> @rrolla Thank you for your advice. If only 1 cloudflare IP is received (fixed cloudflare IP) it might work fine. The problem is that each listener is confirmed to get a different Cloudflare IP. But I tried to use azuracast and enable Cloudflare proxy, listener IP detected in statistics is their real IP, not Cloudflare IP.
> 
> >

But as I understand you can also add subnet eg:

```xml
<x-forwarded-for>162.158.170.1/12</x-forwarded-for>
```

So this can take huge range with ip adresess, totally 1048574 matches
[Subnet calculator](https://jodies.de/ipcalc?host=162.158.170.1&mask1=12&mask2=)

**Comment by gunsar** [comment]
I understand that you have to set a subnet, but what I mean is that the Cloudflare IP received by each country is definitely different, and this is definitely out of our control as Cloudflare users.
i found a comment from @karlheyes  already closed
and try settings like this,

`<x-forwarded-for>*</x-forwarded-for>`

and the problem is solved
Thank's

>>
> 
> But as I understand you can also add subnet eg:
> 
> ```
> <x-forwarded-for>162.158.170.1/12</x-forwarded-for>
> ```
> 
> So this can take huge range with ip adresess, totally 1048574 matches [Subnet calculator](https://jodies.de/ipcalc?host=162.158.170.1&mask1=12&mask2=)

**Comment by gunsar** [comment]
https://github.com/karlheyes/icecast-kh/pull/233#issuecomment-617917587

**Comment by rrolla** [comment]
Nice didn't know about wildcard :)
