### ISSUE TITLE
kh17-pre

### ISSUE THREAD

**Issue by karlheyes** [karlheyes/icecast-kh#381]
Running icecast-2.4.0-kh17-pre3_win64_setup.exe

Something is wrong with the response headers. Content-Lenght is limited to 4000 and every page is truncated. 

![image](https://user-images.githubusercontent.com/20712573/212349548-ea3d0e96-839c-4171-9dd2-ef1b85d7a798.png)

_Originally posted by @jjkbssn in https://github.com/karlheyes/icecast-kh/issues/378#issuecomment-1381982683_

**Comment by karlheyes** [comment]
verified as an issue, seems to be related to xsl only.  Checking...

**Comment by karlheyes** [comment]
ok, I have a fix committed for that.  Older code getting in the way. I'll do a windows build shortly and let you know

**Comment by gunsar** [comment]
I checked the Windows version, it's true that there seems to be a problem with the xsl. I checked the Clients List, the number of listeners should be 20 listeners, when I click on it the data only appears partially, and the cut to the next line is gone including the footer is also gone

![Screenshot 2023-01-13 225542](https://user-images.githubusercontent.com/56213562/212364328-b911f094-66ac-425b-b06a-412e38ed2dcb.jpg)

**Comment by karlheyes** [comment]
I have done a pre5 build to verify things are working as intended so

karlheyes.github.io/icecast-2.4.0-kh17pre5_win64_setup.exe

**Comment by gunsar** [comment]
> I have done a pre5 build to verify things are working as intended so
> 
> karlheyes.github.io/icecast-2.4.0-kh17pre5_win64_setup.exe

thank you, the kh17pre5 version is close to perfect in my experiments, both Windows64 and Linux versions. very cool

**Comment by jjkbssn** [comment]
> I have done a pre5 build to verify things are working as intended so
> 
> karlheyes.github.io/icecast-2.4.0-kh17pre5_win64_setup.exe

Thank you. Issue solved!
