### ISSUE TITLE
kh17.1

### ISSUE THREAD

**Issue by gunsar** [karlheyes/icecast-kh#388]
@karlheyes kh17.1 trial
some admin xsl display problem

http://192.168.8.233:8000/admin/listmounts.xsl
�|:�|:�;|:�;|:92.168.8.233:8000 Connection: keep-alive User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36 Accept: text/css,*/*;q=0.1 Referer: http://192.168.8.233:8000/adminbar.html Accept-Encoding: gzip, deflate Accept-Language: id-ID,id;q=0.9,en-ID;q=0.8,en;q=0.7,en-US;q=0.6,ar;q=0.5

http://192.168.8.233:8000/admin/logs.xsl
Access log
unknown log
Error log
unknown log

**Comment by karlheyes** [comment]
I did fix an issue around the 17.1 update which had this problem and I did retag it but I've fixed a few other things now and 17.2 is up

**Comment by karlheyes** [comment]
fixed that.  junk uninitialized data getting attached to the headers.  you should see that on the master tree now

**Comment by karlheyes** [comment]
reverted a commit which was causing that.  trying to avoid a minor memory leak. Will resolve that another way.

karl.
