### ISSUE TITLE
Empty title (now playing)

### ISSUE THREAD

**Issue by donostiarra2** [karlheyes/icecast-kh#391]
Hi! I'm using liquidsoap for autodj. I've upgraded from KH17 to KH17.2, and "Currently playing:" tag is always empty in status and JSON. Back to 17 works fine again.

**Comment by karlheyes** [comment]
thanks, yes, confirmed and should be fixed in master

karl

**Comment by karlheyes** [comment]
kh18 is out now with that, so I'll close this
