### ISSUE TITLE
Issue when connecting with wrong password

### ISSUE THREAD

**Issue by Daniel-Noethen** [karlheyes/icecast-kh#394]
Hello,

before commit e2d64cd the server answered with the following message when connecting with a wrong password 
using the PUT method.

```
HTTP/1.1 100 Continue

HTTP/1.1 401 Authentication Required
Connection: Close
Date: Wed, 01 Feb 2023 16:28:52 GMT
Content-Type: text/html
WWW-Authenticate: Basic realm="Icecast 2.4.0-kh17"
Content-Length: 0
```
Now since e2d64cd the server answers with

```
HTTP/1.1 100 Continue
Date: Wed, 01 Feb 2023 16:26:42 GMT
Content-Type: text/html
Content-Length: 0
```

The line `HTTP/1.1 401 Authentication Required` is missing which confuses my clients. 

Is this behaviour intended? 

Best,
Daniel

**Comment by karlheyes** [comment]
intended no.  I'll fix shortly, the 1xx codes have to be treated differently,  so I just need to flush out the specs on that.

karl

**Comment by karlheyes** [comment]
should be fixed now in master tree

**Comment by Daniel-Noethen** [comment]
I can confirm. Thanks again!
