### ISSUE TITLE
Incorrect header when retrieving status-json.xsl

### ISSUE THREAD

**Issue by DroidU** [karlheyes/icecast-kh#395]
Curl 7.87.0 in Debian 12, does not download the status-json page because it gives a "Header without colon" error message.
With a different version of curl, the page downloads, but the header is indeed wrong.

HTTP/1.1 200 OK
Server: Icecast
Connection: Close
Pragma: no-cache
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, private
Vary: Origin
Date: Wed, 01 Feb 2023 18:00:52 GMT
Content-Type: application/json; charset=UTF-8
**content-disposition: attachment; filename="Content-Disposition: attachment; filename="file.json"
"**
Content-Length: 673

**Comment by karlheyes** [comment]
that should be fixed in master now
