### ISSUE TITLE
kh18 crashes if "authentication type="command""

### ISSUE THREAD

**Issue by DroidU** [karlheyes/icecast-kh#396]
If the `<authentication type="command">` option is configured on one of the mountpoints, it will crash immediately when the client connects.

config:
[https://pastebin.com/ge2idqJF](url)

log:
[https://pastebin.com/GnCwhh3X](url)

You can specify something else instead of /bin/false in the example, it will still crash.

**Comment by karlheyes** [comment]
can you verify this against kh18.1, tagged on github
