### ISSUE TITLE
Double listener counts in Safari - Byte Range request

### ISSUE THREAD

**Issue by olliekav** [karlheyes/icecast-kh#400]
![double-counts](https://user-images.githubusercontent.com/9005/220587513-4613da7c-8609-4ff5-aef4-30a2a15ae3db.png)

We are currently seeing double stats for listener counts in Safari / iOS that started to happen after in Safari v15/16. From the network logs above it looks like the Byte Range request continues to load as well as the stream.

Does anyone have any insight on this, or how we could avoid it?

These are the headers for the Byte-Range request, could this be avoided by returning a 206 partial content here, is this even possible?

![Byte Range request headers](https://user-images.githubusercontent.com/9005/220589489-4aa09c4b-45eb-48ce-9c9e-f3fa85e8685e.png)

**Comment by karlheyes** [comment]
Unsure which version you tried with, but I get a 206 here and 2 bytes.  I've just cut pre-release 18.2 to make sure all the latest bits are in.

karl.

**Comment by olliekav** [comment]
Thanks Karl. We were on `kh15`, but we just upgraded to `kh18` on our staging env and still seeing the same issue with a 200 response. 

Are there any config changes we need to make here? Otherwise must be an issue our end 👍

**Comment by olliekav** [comment]
So, it looks like the 18.2 pre-release fixes this!

Thanks Karl, we'll wait for this to hit full release then we can do some further testing 👌
