### ISSUE TITLE
kh-19: The server crashes after visiting the status page.

### ISSUE THREAD

**Issue by DroidU** [karlheyes/icecast-kh#403]
A similar bug appeared as the one I reported with the kh-16. The difference now is that no reload is required. If I visit the status page, it appears, and then it immediately crashes.

Config file: https://pastebin.com/bFxzrzfH

I tested several versions between kh-16 and the current one. kh-17.1 seems to be the last one that works well.

**Comment by karlheyes** [comment]
a lock in-balance, that should be resolved in master now.  I'll verify a few lock checks before doing another update, so you can verify that.

karl

**Comment by karlheyes** [comment]
did you try the master, which is kh19 with a fix?

karl.

**Comment by Vyacheslav-S** [comment]
> The difference now is that no reload is required. If I visit the status page, it appears, and then it immediately crashes.

I Confirm. Just now updated to release:
https://github.com/karlheyes/icecast-kh/releases/tag/icecast-2.4.0-kh19

**Comment by Vyacheslav-S** [comment]
Now I have compiled the package from the commit:
https://github.com/karlheyes/icecast-kh/commit/cf8ae43d2ee6c3f337496522c09008d977d1d970
 And crashes again.

**Comment by tjharman** [comment]
Can confirm the latest commit fixes the issue.

**Comment by DroidU** [comment]
It has changed, but not for the better.
In the case of the following configuration, the server does not respond after reloading.
https://pastebin.com/SXnugs5L

**Comment by karlheyes** [comment]
@DroidU checked a couple of use cases there. chunked transfers appear to be making a mess of things so will work around that, will use 1.0 instead and increase the max headers in underlying libs as you seem to be at the limit.

pushed to master.  your config seems to be running ok here.

karl

**Comment by karlheyes** [comment]
@DroidU I take it you use the admin link for reload?

**Comment by karlheyes** [comment]
ok, I think that should resolve the issue fully.  The change in kh19 was correct but incomplete, which caused an imbalance. I've increased the headers possible and done some flushing out of the code.  

master tree now updated.

**Comment by DroidU** [comment]
> @DroidU I take it you use the admin link for reload?

It was also bad with admin link and kill -HUP.
The update seems to be good now.

**Comment by tjharman** [comment]
Don't hate me Karl (I love the work you put into this, thank you so much) but the latest kh20 still annouces itself as kh19 :)

**Comment by karlheyes** [comment]
no, my fault,  I missed a push for the actual version changes.  As the tag was already pushed I'll stamp a 20.1 which is just the same just with the version update. 

karl
