### ISSUE TITLE
Web interface elements listed as sources in stats file

### ISSUE THREAD

**Issue by glitch59** [karlheyes/icecast-kh#406]
Regarding version: icecast-kh-icecast-2.4.0-kh20.2.

When accessing the admin page: /admin/
The items loaded for the web interface, are added as sources to the source list overview.

They become visible on the /admin/ page if you refresh a few times. 
Also they become visible in: /admin/status.xml

For example:
```
  <source mount="file-/images/corner_bottomleft.jpg">
    <outgoing_kbitrate>0</outgoing_kbitrate>
  </source>
  <source mount="file-/images/corner_bottomright.jpg">
    <outgoing_kbitrate>0</outgoing_kbitrate>
  </source>
  <source mount="file-/images/corner_topleft.jpg">
    <outgoing_kbitrate>0</outgoing_kbitrate>
  </source>
  <source mount="file-/images/corner_topright.jpg">
    <outgoing_kbitrate>0</outgoing_kbitrate>
  </source>
  <source mount="file-/images/tunein.png">
    <outgoing_kbitrate>0</outgoing_kbitrate>
  </source>
  <source mount="file-/style.css">
    <outgoing_kbitrate>0</outgoing_kbitrate>
  </source>
```  
This is not a breaking issue, but it does create non existing mount points in the stats file.

Please consider looking at this in a feature update.

Thanks for the great work!
Best regards, Sven

**Comment by karlheyes** [comment]
just done a pre-release kh20.3 which should resolve this.  If you can confirm

karl

**Comment by glitch59** [comment]
Just tested it: the issue is resolved.
Thank you!
Best Sven.
