### ISSUE TITLE
kh20.4: Browser tries to download XSL file when loading stats, rather than display it

### ISSUE THREAD

**Issue by Nick6489** [karlheyes/icecast-kh#410]
This issue publicly exhibits itself on [this server](https://listen.HKCRadio.com). I recognize that KH20.5 is out, but I can't tell by the changelog if this was fixed?

**Comment by karlheyes** [comment]
this looks like stale information hanging around in the xsl cache. An xspf disposition header for the status xsl.  Can you get a level 4 log from this?  Do you have many xsl links requested, even of they are missing?

karl

**Comment by karlheyes** [comment]
just to clarify, there was a fix post 20.4 that resolved the filename aspect in the disposition, that may be a factor here

karl

**Comment by Nick6489** [comment]
I have just updated. I will check back in about two weeks, the last time I updated the thing it took that long for it to exhibit the issue.

**Comment by karlheyes** [comment]
I've reworked the xsl caching code to split the locking some more as there were some race issues there.  It looks to be much better now in the master tree. 

karl

**Comment by Nick6489** [comment]
Once again, I've updated. I will get back to you in a week if it doesn't work (the issue does have some lag time to exhibit).
