### ISSUE TITLE
UTF8 data probably incorrect charcter set 

### ISSUE THREAD

**Issue by onur58** [karlheyes/icecast-kh#411]
Hi 

We are facing some charset issues with 2.4.0 KH20 (v.19)

It doesn't display Umlaute like "ä,ö,ü," and french characters etc.:

WARN stats/stats_set_conv seen non-UTF8 data, probably incorrect charcter set (title, Radio Musikwelle - Die schnsten Melodien fr Sie

Wrong title: title, Radio Musikwelle - Die schnsten Melodien fr Sie
Correct title should look like: title, Radio Musikwelle - Die sch**ö**nsten Melodien f**ü**r Sie

I already configured the charset modification in mount settings like this example but it doesn't help:
<mount>
                <mount-name>/r2/radio2/mp3_128</mount-name>
                <fallback-mount>/r1/radio2/mp3_128</fallback-mount>
                <fallback-override>1</fallback-override>
                <charset>UTF-8</charset>
        </mount>

Do you have any idea? 

Many thanks for your support :-)

**Comment by karlheyes** [comment]
do you know what charset the incoming title is in?   the default is to assume utf8 but if you are providing something different and there is no recognised method of notification or it being different then you can have this type of problem.

determine if it is a relay or source and what the content is there.  Obviously utf8 allows for any but historically many have
assumed something like latin1

karl.

**Comment by onur58** [comment]
Hi Karl

Many thanks for your feedback. It's a relay server which connects to source Icecast Server in different location. We have same setup and config with Icecast 2.4.0 Kh10 and it is working fine without adding charset in the config for mp3 and AAC streams. Therefore it's really strange for us. Here is an example output from config file:

` <relay>
                <server>_IP of Source Server_</server>
                <port>8000</port>
                <mount>/rr/mp3_128</mount>
                <local-mount>/r1/rr/mp3_128</local-mount>
                <retry-delay>10</retry-delay>
        </relay>
                <relay>
                <server>_IP of Source Server_</server>
                <port>8000</port>
                <mount>/rr/mp3_128</mount>
                <local-mount>/r2/rr/mp3_128</local-mount>
                <retry-delay>10</retry-delay>
        </relay>
                <mount>
                <mount-name>/r2/rr/mp3_128</mount-name>
                <fallback-mount>/r1/rr/mp3_128</fallback-mount>
                <fallback-override>1</fallback-override>
                _ Tested with <charset>ISO8859-1</charset> and <charset>UTF-8</charset> --> got the same result _
        </mount>`

Should we modify on the source server or somewhere else in the config file?

Many thanks for your support.

**Comment by karlheyes** [comment]
assuming kh10 was fine then use  a charset of ISO8859-1 as that was the default at that time

karl

**Comment by onur58** [comment]
Hi Karl, 
Sorry for my late response (happy easter! :-)) 
If we assume that default charset for previous versions from kh10 was ISO8859-1 then it should be reproducible. I extended the charset settings with  `<charset>ISO8859-1</charset>` but it was the same result. 

Our Setup which works fine so far:

(1) MUXIP Signal Encoder for AAC and MP3 (live streams) ---> 
(2) Source Master with local mounts like stream1.aac  and stream1.mp3 (Icecast 2.4.4 **not kh** on Linux) --->
(3) Master relay Server with relay mounts from Source Master (2.4.0 kh10 on Linux) ---> 
(4) 10x Icecast Edge Server, we named "LSA CDN" relaying from Master relay Server (2.4 kh10 on Linux)

What I did until today was to update point (3) and point (4) to version 2.4.0 KH20 with charset settings to ISO8859-1 and also to UTF-8 but the result was the same  "WARN stats/stats_set_conv seen non-UTF8 data, probably incorrect charcter set" i got this message also with ISO8859-1 charset. 

Therefore I assume that the charset settings will be not applied on the point (3) and (4). What would you do as next? :-) or where can I verify the incomming ICY metadata charset?

Many thanks again for your great support Karl. 

BR,
Onur

**Comment by onur58** [comment]
Hi Karl, 

The source Master point (1) is using latin1 per Default in 2.4.4 (not KH). So that would mean that our Master Relay (3) and Icecast Edges (4) assuming UTF-8 per default 2.4.0 KH20 and can not handle it. So my main question is, where and how can I change the charset for our Master Relay (3) and Icecast Edges (4) the default charset from UTF-8 to latin1? I found this entry https://github.com/karlheyes/icecast-kh/issues/249#issuecomment-614984263 from you but it's not clearly defined (sorry I am not a developer) :-) 

I tested with `<charset>ISO8859-1</charset>` in mount section of Master Relay (3) and Icecast Edges (4). I will also share the icecast.xml config of all nodes here:

`Icecast Source Master (Point 2)

<icecast>
    <limits>
        <clients>1000</clients>
        <sources>150</sources>
        <threadpool>5</threadpool>
        <queue-size>524288</queue-size>
        <client-timeout>30</client-timeout>
        <header-timeout>15</header-timeout>
        <source-timeout>10</source-timeout>
        <burst-on-connect>1</burst-on-connect>
        <burst-size>65535</burst-size>
    </limits>
    <authentication>
        <source-password>xyz</source-password>
        <relay-password>xyz</relay-password>
        <admin-user>xyz</admin-user>
        <admin-password>xyz</admin-password>
    </authentication>


    <hostname>hostname of the Source Master Icecast</hostname>
    <location>xyz</location>

    
    <listen-socket>
        <port>8000</port>
        <bind-address>127.0.0.1</bind-address>
        
    </listen-socket>
	<listen-socket>
        <port>8000</port>
        <bind-address>IP of the Source Master Icecast</bind-address>
        
    </listen-socket>
 
    
    <mount>
	<mount-name>/stream1</mount-name>
	<source-timeout>4</source-timeout>
    </mount>
    <relay>
      <server>10.153.5.244</server>
      <port>8000</port>
      <mount>/stream1_Room1</mount>
      <local-mount>/stream1/mp3_128</local-mount>
    </relay>
 


Icecast Master Relay (Point 3)

<icecast>
  <location>xyz</location>
  <hostname>streaming.xyz </hostname>
  <admin>servicedesk@xyz</admin>
  <listen-socket>
    <port>80</port>
  </listen-socket>
  <authentication>
    <admin-user>xyz</admin-user>
    <admin-password>xyz</admin-password>
    <source-password>xyz</source-password>
  </authentication>
  <limits>
    <clients>3700</clients>
    <sources>1000</sources>
    <header-timeout>10</header-timeout>
    <source-timeout>10</source-timeout>
    <burst-size>76459</burst-size>
  </limits>
  <security>
    <chroot>0</chroot>
    <changeowner>
      <user>xyz</user>
      <group>xyz</group>
    </changeowner>
  </security>
  <paths>
    <logdir>/var/log/icecast</logdir>
    <webroot>/usr/share/icecast/web</webroot>
    <adminroot>/usr/share/icecast/admin</adminroot>
    <pidfile>/var/run/icecast.pid</pidfile>
                <alias source="/info" dest="/status.xsl" />
        <alias source="/" dest="/welcome.html" />
  </paths>
  <logging>
    <accesslog>access.log</accesslog>
    <errorlog>error.log</errorlog>
    <loglevel>3</loglevel> 
    <logsize>10240</logsize>
  </logging>



        <relay>
                <server>IP of primary source Server</server>
                <port>8000</port>
                <mount>/stream1/mp3_128</mount>
                <local-mount>/r1/stream1/mp3_128</local-mount>
                <retry-delay>10</retry-delay>
        </relay>
                <relay>
                <server>IP of secondary source Server</server>
                <port>8000</port>
                <mount>/stream1/mp3_128</mount>
                <local-mount>/r2/stream1/mp3_128</local-mount>
                <retry-delay>10</retry-delay>
        </relay>
                <mount>
                <mount-name>/r2/stream1/mp3_128</mount-name>
                <fallback-mount>/r1/stream1/mp3_128</fallback-mount>
                <fallback-override>1</fallback-override>
               <charset>ISO8859-1</charset> -->not working
	

        </mount>
		
		

Icecast Edge Server (Point 4)

<icecast>
  <location>xyz</location>
  <hostname>streaming.xyz</hostname>
  <admin>servicedesk@xyz</admin>
  <listen-socket>
    <port>80</port>
  </listen-socket>
    <listen-socket>
    <port>443</port>
    <ssl>1</ssl>
  </listen-socket>
    <authentication>
    <admin-user>xyz</admin-user>
    <admin-password>xyz</admin-password>
    <source-password>xyz</source-password>
  </authentication>
  <limits>
    <clients>8000</clients>
    <sources>1000</sources>
    <header-timeout>5</header-timeout>
    <source-timeout>5</source-timeout>
    <burst-size>76459</burst-size>
  </limits>
  <security>
    <chroot>0</chroot>
    <changeowner>
      <user>xyz</user>
      <group>xyz</group>
    </changeowner>
  </security>
  <paths>
    <logdir>/var/log/icecast</logdir>
    <webroot>/usr/share/icecast/web</webroot>
    <adminroot>/usr/share/icecast/admin</adminroot>
    <pidfile>/var/run/icecast.pid</pidfile>
                <alias source="/info" dest="/status.xsl" />
        <alias source="/" dest="/welcome.html" />
        <ssl-certificate>/etc/pki/tls/certs/xyz.pem</ssl-certificate>
    
      </paths>
  <logging>
    <accesslog>access.log</accesslog>
    <errorlog>error.log</errorlog>
    <loglevel>3</loglevel> 
    <logsize>10240</logsize>
  </logging>


        <relay>
                <server>Ip of primary Icecast Master Relay</server>
                <port>80</port>
                <mount>/r1/stream1/mp3_128</mount>
                <local-mount>/s/stream1/mp3_128</local-mount>
                <retry-delay>10</retry-delay>
                <on-demand>0</on-demand>
        </relay>
        <relay>
                <server>Ip of secondary Icecast Master Relay</server>
                <port>80</port>
                <mount>/r2/stream1/mp3_128</mount>
                <local-mount>/m/stream1/mp3_128</local-mount>
                <retry-delay>10</retry-delay>
                <on-demand>0</on-demand>
        </relay>

    <mount>
        <mount-name>/m/stream1/mp3_128</mount-name>
        <fallback-mount>/s/stream1/mp3_128</fallback-mount>
        <fallback-override>1</fallback-override>
        <max-listener-duration>68400</max-listener-duration>
		<charset>ISO8859-1</charset> -->not working
            </mount>
    
`

**Comment by karlheyes** [comment]
do you have a stream I can relay locally to check against?

karl

**Comment by onur58** [comment]
Hi Karl, you should receive an e-mail with the test streams. 

Many thanks for your support.

BR,
Onur

**Comment by karlheyes** [comment]
ok, that looks to be fixed now. I've committed that fix into the master tree.  Broke in kh17 from the look of it, but was a minor fix

**Comment by onur58** [comment]
many thanks for the minor fix Karl, but it's the same for AAC stream. Your change will fix it also for AAC streams charset and will you create a new version like kh21 ?

**Comment by karlheyes** [comment]
aac and mp3 are handled in the same routine, so the charset handling issue would apply in the same way.  Im waiting on  feedback from something else, and if that is ok then kh21 will be released

karl

**Comment by onur58** [comment]
Hi Karl, that sounds really good :-) Many thanks again for your support.

**Comment by karlheyes** [comment]
kh21 is up

karl.

**Comment by onur58** [comment]
Hi Karl,

Many thanks for fixing this issue. It works with latin1 charset on the Icecast Edge mounts. 

BR,
Onur
