### ISSUE TITLE
Change listen URL reported to YP? (Needed if proxying or reducing open ports)

### ISSUE THREAD

**Issue by Moonbase59** [karlheyes/icecast-kh#417]
As I mentioned over at AzuraCast in https://github.com/AzuraCast/AzuraCast/issues/6241, many of us nowadays live behind proxies (Nginx, Apache, NPM, etc.) that handle SSL cert generation & updates, and we probably all wish to reduce the number of open ports, or might even be forced to only use 80 or 443.

So I reckon the time of "brute-force-generating" a listen URL by constructing it from the host name, a port, and the mount point name, and using http://, as Icecast does, is a little outdated.

For instance, I use AzuraCast and have a listening URL of (name changed):
```
https://radio.testradio.net/listen/testradio/radio.mp3
```
which works great with only port 443 open, and could even be embedded in a https:// website.

Icecast. nevertheless, constructs a listener URL of:
```
http://radio.testradio.net:8000/radio.mp3
```
and reports _that_ to [dir.xiph.org](https://dir.xiph.org), the Icecast Yellow Pages.

This would need
- opening port 8000
- a http:// connection
- an URL different from what we communicate to use

It would also
- block listeners on providers that disallow all but a few selected ports (think mobile)
- block listeners on corporate or guest networks that are often very restrictive (i.e., allow only 80, 443 and email ports)

**My questions:**
- **Is it possible to change the listener URL** (maybe by some mount-specific XML parameter in `icecast.xml` like `<listenurl>…</listenurl>`)?
- **If not, could something like this be implemented?**

I’ve seen lots of different URLs on dir.xiph.org, so there must surely be a way… And I think _many_ stations would benefit from that!

Here are some random examples:

- `http://s37.derstream.net/live.mp3` (no port)
- `http://web.radio.antennevorarlberg.at/av-2010er/stream/mp3?aggregator=icecastdirectory` (subfolders, no port, added parameter)
- `https://edge16.streamonkey.net/charivaristream-kult80er/stream/mp3?aggregator=icecastdirectory` (https://, subfolder, added parameter)

**Comment by karlheyes** [comment]
I managed to get around to this. I have added a listenurl tag to the mount block to allow for specifying you own url sent to the directory.   Obviously the directory will do some level of checking to make sure it matches but tag specifies the url in the info to the directory.  It is currently in the master tree if you want to try it immediately, or wait until the next [pre-]release.

karl.

**Comment by Moonbase59** [comment]
@karlheyes Wow, thanks for that, much appreciated! Will soon check it out.

**Comment by Moonbase59** [comment]
Hi Karl, sorry, it took a while until kh21.8 was officially integrated into AzuraCast.

I’m very happy to say that using `<listenurl>…</listenurl>` per mountpoint is working very well so far with

- dir.xiph.org
- icecast-yp.internet-radio.com

Station and now-playing info as well as the player links work on both, and finally our stations can be correctly listed. Thanks ever so much for implementing this!
