### ISSUE TITLE
icecast-2.4.0-kh21_win32_setup ... Please

### ISSUE THREAD

**Issue by Josodl** [karlheyes/icecast-kh#419]
Hi friend. Can you make a win32 setup of this new version?
I still have a VM win 2003 server in production, extremely stable and I would like updates.
Sorry for being late... 

Thanks and congratulations by your hard work in KH branch

**Comment by Josodl** [comment]
I know I'm late with this 2003 server. As it always ran stably, it ended up being in the park. I don't know if it's worth your effort to get a win32 version compatible with it. it's possible that I'm the only one in the community still using this legacy system. Thank you anyway!!!

**Comment by boteman** [comment]
Win2003 32-bit is probably a security problem considering the many threats present on the Internet. I hope you have a very tight firewall protecting it. The developers that I talk to refuse to write any 32-bit code these days.

**Comment by Vishin44** [comment]
The "plug" does not work when the flow is interrupted.

Hi! I immediately say that I am writing a comment through a translator)) Please fix the bug that prevents the stub file from running when the stream is interrupted...
That's what I mean... <fallback-mount>/fallback.mp3</fallback-mount> In the version [icecast-2.4.0-kh15] everything works!

**Comment by Vishin44** [comment]
> it seems better that we use kh17, of all my experiments the smoothest for all (windows, linux, azuracast panel, centovacast panel)

good!)) I'll try! But I've been using kh15 for a long time))

**Comment by karlheyes** [comment]
Just been working through some log code for a while, seems to be there now.  I think the fix for the older builds just requires a dll to be distributed.  It's not referenced by icecast directly but the the dependant libs like ssl refer to it.  The DLL seems to be present on newer platforms.  I'll do an interim build for windows later today.  Windows users can then confirm that its running ok.   AFAIK, the fallback handling is working well in latest updates

karl.

**Comment by karlheyes** [comment]
I've uploaded a pre-release.  Can windows users verify the install works correctly.  Even with older windows should be ok. 

karl.

**Comment by karlheyes** [comment]
Assuming the windows installer even on pre-windows 8 works well then fine.  I have now fixed a windows log cycle bug and I've uploaded both 32/64 bit for the 21.5 pre-release

karl

**Comment by karlheyes** [comment]
I'll assume the builds are all ok. open a report if this is an issue.

karl
