### ISSUE TITLE
No way to use listener URL auth and allow multiple connections for one account

### ISSUE THREAD

**Issue by radioboss** [karlheyes/icecast-kh#421]
Icecast URL AUTH always checks for "duplicate" users and there's no way to allow connection users with the same username. This is a limitation. I created a small pull request that adds a config option to control this: https://github.com/karlheyes/icecast-kh/pull/420

**Comment by karlheyes** [comment]
this sounds like the allow_duplicate_users setting which is actually a general auth setting.  It is disabled by default so it would prevent multiple connections with the same username.   If that is what you want then you can set it in the options, I suppose the default could be made to allow.   This should already work. 

karl

**Comment by radioboss** [comment]
Oops, sorry didn't know about that :)
