### ISSUE TITLE
Bug in url_stream_auth function

### ISSUE THREAD

**Issue by radioboss** [karlheyes/icecast-kh#422]
auth_url.c, on line 766:
`curl_easy_setopt (atd->curl, CURLOPT_URL, url->stream_auth);`

I guess it should be "url" field, not the struct itself:
`curl_easy_setopt (atd->curl, CURLOPT_URL, url->stream_auth.url);`

**Comment by karlheyes** [comment]
indeed, nice one spotted.  It's not heavily used and seems to of been broken since about 21.2 but obviously good. 

Will commit shortly

karl

**Comment by karlheyes** [comment]
in the latest pre-release now

karl
