### ISSUE TITLE
Icecast 2.3.3-kh9 never recovering from "too many clients awaiting authentication"-state

### ISSUE THREAD

**Issue by niko** [karlheyes/icecast-kh#64]
On serveral occasions we encountered an issue where Icecast 2.3.3-kh9 would go into "too many clients awaiting authentication"-state and never recover. Over the course of about 1,5 hours our authentication service didn't receive a single requests while all new listeners got a 403. This is especially unfortunate in combination with issue #62. It seems as if `mountinfo->auth->pending_count` (https://github.com/karlheyes/icecast-kh/blob/92697d6f99f66c603389387d142b8199400142b6/src/auth.c#L608) would not count down and return to a value that allows new auth requests.

**Comment by mr-deamon** [comment]
Is it possible that this has been fixed when working with URL, but might still happen when using command-based authentication? Or am i required to use listener_remove if using listener_add? I am currently on KH11 and am still getting these messages. Current workaround is a icecast reload if it happens, it looks like the queue gets cleared this way

chris

**Comment by musarano** [comment]
Thank You  Karl & Chris,

Im trying the Icecast 2.3.3-kh12pre  Version Now, and see how it goes... So
far, no issues yet... (Windows 2008 Enterprise ED R2 64bits @ 128G Ram

-Dalton

**Comment by mr-deamon** [comment]
Oh, don't thank me :) But you are using url-auth, don't you?

**Comment by musarano** [comment]
Yes, im using both with and without, depends on the case of the mount-point.
