### ISSUE TITLE
Is it possible to show error, message with command auth without auth window?

### ISSUE THREAD

**Issue by alvassin** [karlheyes/icecast-kh#69]
Hello Karl,

Currently i am using current configuration for my mounts:
```
<authentication type="command">
    <option name="listener_add" value="icecast-auth.php"/> 
    <option name="handlers" value="1"/> 
</authentication>
```

And when my auth script returns message with reason:
```
icecast-auth-message: {any text}\n\n
```

Icecast sends auth headers and basic auth window is displayed. It is confusing, for example, when i need to limit listeners dynamically (they are in panic because of this auth window).

Is it possible somehow to configure icecast to return specifiec header?

Thanks in advance!

P.S. Icecast version: Icecast 2.3.3-kh9-20131122232644

**Comment by alvassin** [comment]
Hello, Karl!

Today when i tried to move client via cmd auth handler to another mountpoint i ran into issue: icecast returns 401 answer and asks client for credentials.

I return to icecast `Mountpoint: /mountpoint-name\n\n`
Is this a bug? I use Icecast 2.4.0-kh1-20150616004931 version.

**Comment by karlheyes** [comment]
Just for clarity, did you also return a icecast-auth-user: line and if so what was the exact return?

karl.

**Comment by alvassin** [comment]
@karlheyes nope, that was a mistake. Thanks a lot for suggestion!

**Comment by himanshuvirmani** [comment]
I am using auth for icecast with Android Media Player and android media player retries every 3 seconds because the response code is 401. Is there a way I can send some other code which leads to media error rather than infinite retrying? I am sending 403 from my auth script

Icecast Logs

[2016-02-01  17:14:53] INFO auth/auth_add_listener adding client for authentication
[2016-02-01  17:14:53] INFO auth/queue_auth_client auth on /XXXXXX has 1 pending
[2016-02-01  17:14:53] INFO auth_url/url_add_listener client auth (http://api.XXX.XXX) failed with "403"

**Comment by karlheyes** [comment]
make your auth return something like

HTTP 200 OK
icecast-auth-message: 403 You shall not Paaassss!!!

karl

**Comment by himanshuvirmani** [comment]
I can do that..but will this make sure that android media player receives different response code. This is because Android Media Player is an internal android code where I cannot read headers and then change actions.

**Comment by karlheyes** [comment]
Having 403 at the beginning of the message will tell the kh icecast to send a 403 back to the listener with the message, different codes have different meanings but if there is something that can be useful that is not done then let me know.

karl.

**Comment by himanshuvirmani** [comment]
Thanks Karl for the help,

Is this feature only available in icecast-kh and not the normal icecast? Currently I have installed icecast2 using apt-get (Icecast 2.3.3). Reason for clarifying is because I have tried what you said with the icecast2 and it still sends 401 to listener client.

**Comment by himanshuvirmani** [comment]
Hey Karl,
Awaiting your reply on above queries..
Thanks in advance. :)

**Comment by karlheyes** [comment]
yes, I doubt that 2.4.x has that in either.

karl.

**Comment by himanshuvirmani** [comment]
Cool..Thanks..Will try icecast-kh and will keep you posted on the result.. :)
