### ISSUE TITLE
Generated M3U-Files contain HTTP header information

### ISSUE THREAD

**Issue by ClemensSchneider** [karlheyes/icecast-kh#86]
Hi,
I'm having a strange issue with the m3u files being generated by Icecast 2.3.3-kh10.
These do contain HTTP header information. The file contents do look like:

    HTTP/1.0 200 OK
    Content-Type: audio/x-mpegurl

    http://my-streaming-server.com:80/radio.aac.160

Any idea why the header-information could be sneaking into the file contents?

Regards,

Clemens

**Comment by karlheyes** [comment]
2.3.99.5 looks to be an old prerelease, reopen if issue persists.

karl.
