### ISSUE TITLE
Unable to get Listener stats in icecast-kh for un4seen bass library. Works ok in icecast2 

### ISSUE THREAD

**Issue by tolew1** [karlheyes/icecast-kh#97]
Hello,

There seems to be a small bug in the response that icecast-kh sends back when listener data is requested from the un4seen bass lib. It works fine in icecast 2.3.2 but not in icecast-kh. We've discovered the reason and posted it in this topic on icecast's forum. Please have a look. It boils down to case sensitivity in the response. See the link for all the details and the proposed fix.  

http://icecast.imux.net/viewtopic.php?t=11969

Please let me know if this can be fixed. 
Thanks

**Comment by karlheyes** [comment]
I'll assume this is working against the master tree for now.  re-open if it's still an issue
